### ISSUE TITLE
Command to rollback the chunk you're standing in.

### ISSUE THREAD

**Issue by creatorfromhell** [PlayPro/CoreProtect#10]
The command should be /co chunk [t:<time frame>] [u:<name>]

**Comment by Intelli** [comment]
There are two options presently for this.

1. Either stand in the middle of the chunk and do `r:7`
2. Make a WE selection of the chunk and use `r:#we`

Adding a separate command just for rolling back chunks is unnecessary, as targeting specific chunks isn't inherently beneficial.
