### ISSUE TITLE
CoreProtect not recognizing FAWE changes

### ISSUE THREAD

**Issue by MarvinKlar** [PlayPro/CoreProtect#106]
I'm using CoreProtect and Fast Async WorldEdit on my server, but I can't see the WorldEdit changes in the CoreProtect lookup.

How to reproduce:
- Install CoreProtect v20.1 and FAWE 21.10.2021 Commit f7a8f6f5 Build 370 Bukkit
- Set `worldedit: true` in `CoreProtect/config.yml` (is already true by default)
- Add `"net.coreprotect.worldedit.CoreProtectLogger"` to `extent.allowed-plugins` in `FastAsyncWorldEdit/config.yml`
- Use the wand tool and e.g. the command `//set 1` to make any changes with FAWE
- Use e.g. the command `/co lookup t:1h` to see latest changes
- The FAWE changes are not present

What I have tried so far:
- Setting `region-restrictions: false` in `FastAsyncWorldEdit/config.yml`
- Adding `CoreProtect` to `region-restrictions-options.exclusive-managers` in `FastAsyncWorldEdit/config.yml`

Am I missing something or is this a bug?

**Comment by vacla** [comment]
Fawe has their own logging + they removed support so it cant show up in coreprotect anymore either

**Comment by vacla** [comment]
Only normal worldedit and async worldedit is supported by CoreProtect regarding Worldedit
