### ISSUE TITLE
Log Pickup not work

### ISSUE THREAD

**Issue by IronDirt** [PlayPro/CoreProtect#112]
Hallo
the pickup items log not work
i drop x1 stone and then I collect it, but it is not logged when I collect it in CoreProtect

image: [https://i.postimg.cc/MG9L2RDf/image.png](https://i.postimg.cc/MG9L2RDf/image.png)

Config CoreProtect in PosteBin: [https://pastebin.com/nNF3q1n9](https://pastebin.com/nNF3q1n9)

**Comment by vacla** [comment]
Is there anything in your logs?

**Comment by IronDirt** [comment]
> Is there anything in your logs?

No anything
latest.log [https://pastebin.com/xV880cPN](https://pastebin.com/xV880cPN)

**Comment by Intelli** [comment]
Please test without any other plugins.

**Comment by IronDirt** [comment]
okey, the problem is pluginj zItemStacker
its possible to add compatibility?

**Comment by Intelli** [comment]
You'll need to contact the developer of that plugin.

Also note, that Spigot/Paper have built in item stacking functionality. Using a plugin is not necessary for item merging.
