### ISSUE TITLE
Translated the Ukrainian localization of the plugin (added uk.yml)

### ISSUE THREAD

**Issue by stiltezh** [PlayPro/CoreProtect#119]
I forked your project and left the translation file in the [lang folder](https://github.com/stiltezh/CoreProtect/blob/master/lang/uk.yml). I would be very happy if you could add it to the main project.

**Comment by Intelli** [comment]
I added the base Ukrainian translation here: https://github.com/PlayPro/CoreProtect/commit/c1a4323ce443bc9e3ad6ec6dc69859d7a4f007db

Please feel free to submit any changes as a PR against that file.
