### ISSUE TITLE
Chat Error

### ISSUE THREAD

**Issue by Anonymo99** [PlayPro/CoreProtect#120]
Hi,
 I updated the plugin to the latest version, when i write in chat i get this error.

https://pastebin.com/y3ujspy4

My paper version:
This server is running Paper version git-Paper-792 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

**Comment by Intelli** [comment]
Should be fixed (untested). Please confirm.

**Comment by Intelli** [comment]
Fixed in v20.3.
