### ISSUE TITLE
CoreProtect not logging explosions

### ISSUE THREAD

**Issue by QuantumZizo** [PlayPro/CoreProtect#123]
Recently I used an extremely powerful TNT cannon, and it decimated a crap ton of land. So I tried to use CoreProtect to undo the damage. But, the rollback did not undo the explosions. I even tried to rollback FOUR HOURS before I used the TNT cannon. It erased the TNT cannon since I built it within four hours, but the explosions were still there. My only choice was to worldedit the ground back to normal. Any way to fix this?

**Comment by QuantumZizo** [comment]
The point is, CoreProtect did not log the explosions, and my tests with only one TNT explosion showed that.

**Comment by QuantumZizo** [comment]
Config was set correctly

**Comment by Intelli** [comment]
Please do the following:

1. Provide a copy of your latest server log.
2. Disable all other plugins, and confirm that explosion logging is still not functioning.

**Comment by QuantumZizo** [comment]
[latest.log](https://github.com/PlayPro/CoreProtect/files/7749306/latest.log)
I unfortunately could not disable all other plugins, as multiverse is required to use multiple worlds but I disabled all the others and the logging still fails.

**Comment by QuantumZizo** [comment]
The log above is from my test session on my server trying to get CoreProtect to work

**Comment by Intelli** [comment]
Unable to replicate using Paper 1.18.1 with CoreProtect v20.3. You likely have something on your server conflicting with explosion logging.

Please either provide exact steps to replicate, or a copy of the server files.

As well, please provide a screenshot of the inspector lookup results.

**Comment by QuantumZizo** [comment]
So it appears that CoreProtect can log the explosions but is unable to rollback the explosions.
![2021-12-21_15 46 40](https://user-images.githubusercontent.com/91835426/147007610-f59743d3-a6f1-4121-bdb5-139eadd8aa66.png)
m

**Comment by Johnibur** [comment]
You basically need to roll that tnt user back. Use u:#tnt with a range.

**Comment by QuantumZizo** [comment]
oh
