### ISSUE TITLE
Top block of grown bamboo has no placement logs

### ISSUE THREAD

**Issue by blazex224** [PlayPro/CoreProtect#129]
When bamboo is placed and grown, it can be rolled back by using u:#bamboo, however, the top block of bamboo has no placement logs. Bamboo grief happened recently where it was placed everywhere, and everything can be rolled back except for the very top block.

![image](https://user-images.githubusercontent.com/20233502/147786112-1e982caf-7317-4946-a045-4e04fedf6625.png)

![image](https://user-images.githubusercontent.com/20233502/147786221-d31f3d2d-f13f-4211-9a15-02b8a026ce9b.png)

![image](https://user-images.githubusercontent.com/20233502/147786248-1747dac1-6729-4a19-8357-d2187875f9c7.png)

The same seems to be true of cactus, though I haven't tested other crops

![image](https://user-images.githubusercontent.com/20233502/147789283-00224c68-1a39-4172-a900-a4014fd73082.png)

**Comment by blazex224** [comment]
This is using CoreProtect version 20.3 and paper-1.18.1-101

**Comment by Intelli** [comment]
Confirmed.

**Comment by Intelli** [comment]
Will be fixed in the next release.
