### ISSUE TITLE
Command /co 1 <page> not working 

### ISSUE THREAD

**Issue by burdoto** [PlayPro/CoreProtect#13]
Whenever I try to run the paging command, I get the error "Command /co 1 not found" even though this is listed as the log pagination command. 
![grafik](https://user-images.githubusercontent.com/42473485/56764286-a7dbad00-67a4-11e9-8bb8-03416d2d19cb.png)

**Comment by Xeyame** [comment]
It's `/co l`

**Comment by Intelli** [comment]
It's /co l 123 (/co lookup 123)
