### ISSUE TITLE
Rework /co inspect permissions

### ISSUE THREAD

**Issue by ChiboYen** [PlayPro/CoreProtect#133]
Currently `coreprotect.inspect` gives permission to use the command `/co inspect`, but there are a few problems with this for many servers:
- `/co inspect` only toggles the inspect mode, if a player loses the permission, they will be stuck in the inspect mode
- Whether or not someone can inspect at that exact moment is not dependent on if they have the `coreprotect.inspect` permission

If possible, could you make `coreprotect.inspect` a permission that is required to inspect items (instead of just a toggle)? A new implementation could look like:
- `/co inspect` still toggles the inspect mode
- If a player does not have `coreprotect.inspect` at the time of inspecting something, it shows a no permission message and disables inspct mode

**Comment by Intelli** [comment]
Makes sense, I'll add a check every time a person attempts an inspection.
