### ISSUE TITLE
[BUG] Block placing when inspecting trapdoors

### ISSUE THREAD

**Issue by HellRayka** [PlayPro/CoreProtect#134]
When I right click on the trapdoor with a block in my hand on shift, the block is placed where I clicked

https://youtu.be/LBH8Iqev-ZQ

**Comment by vacla** [comment]
@HellRayka can you try without any mods? Since you atleast seem to be using some of masa mods, just want to make sure it is nothing with that, also try with just coreprotect

**Comment by vacla** [comment]
Actually, i just remembered, are you running Cardboard?

**Comment by HellRayka** [comment]
> Cardboard

What is cardboard?

**Comment by HellRayka** [comment]
> @HellRayka can you try without any mods? Since you atleast seem to be using some of masa mods, just want to make sure it is nothing with that, also try with just coreprotect

Check -> https://youtu.be/E3GLzfK1yNA

**Comment by vacla** [comment]
> > @HellRayka can you try without any mods? Since you atleast seem to be using some of masa mods, just want to make sure it is nothing with that, also try with just coreprotect
> 
> Check -> https://youtu.be/E3GLzfK1yNA

Can show the list of plugins on your server, mention also which you use: spigot, paper, bukkit

**Comment by HellRayka** [comment]
> 

Same bug on server withput plugins -> paper

I'm using purpur on main server

**Comment by Intelli** [comment]
Fixed in v21
