### ISSUE TITLE
[Bug?] org.sqlite.SQLiteException: [SQLITE_READONLY]  Attempt to write a readonly database (attempt to write a readonly database)

### ISSUE THREAD

**Issue by SleepyCatten** [PlayPro/CoreProtect#135]
Good day,

I keep seeing this warning message appear on my server. Here is a link to the details from the latest log:
https://gist.github.com/SleepyCatten/4fcd0cc03c38bbe4d5c6dcfc3fbac0a4

This server is running Paper version git-Paper-150 (MC: 1.18.1).

Plugins (21): AngelChest, BestTools, ChestSort, Chunky, CoreProtect, Drop2InventoryPlus, floodgate, Geyser-Spigot, HolographicDisplays, LuckPerms, PetMaster, PluralKitMC, ProNouns, ProtocolLib, RoseStacker, StackableItems, VanillaTweaks, Vault, VeinMiner, ViewDistanceTweaks, voicechat

There are 5 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/armor statues v2.8.3.zip (world)], [file/respawning-pets-e630.zip (world)], [file/global-trades.zip (world)]

I am wondering whether this might be an incompatibility with a plugin called AngelChest, but wanted to report it to yourselves to review also.

Apologies in advance, as I am not a developer and do not code, so have little insight on the issue itself.

Kind regards

**Comment by Intelli** [comment]
https://www.sqlite.org/rescode.html#readonly

That means the plugin is unable to write to the database.db file. You may want to double check your file permissions.

**Comment by SleepyCatten** [comment]
Hi. Thanks for the reply. This error doesn't occur most of the time. As far as I can tell, it only seems to occur intermittently, such as when a player has an unclaimed AngelChest for a while.

**Comment by SleepyCatten** [comment]
Hi. I've checked the file permissions and ensured that all all users (system, user, admin) have full control permissions.
