### ISSUE TITLE
[Bug] Chat links doesn't work after installing CoreProtect

### ISSUE THREAD

**Issue by braydel** [PlayPro/CoreProtect#139]
Hi all, I've been using CoreProtect for a while, and I've isolated this issue to the CoreProtect plugin and even (kinda) "patched" it on my source. 

Basically, when a player posts a link in the chat, you should be able to click on the link and open it in your default browser. This isn't working for CoreProtect because for some reason the PlayerChatListener and the PlayerCommandListener is preventing this chat feature of working. 

So, if I comment out this code from the ListenerHandler then the default implementation where links are clickable in chat works. 
`pluginManager.registerEvents(new PlayerChatListener(), plugin);
pluginManager.registerEvents(new PlayerCommandListener(), plugin);`

I'm guessing this is because CoreProtect is taking the users chat and then copying the message canceling the event and then directly sending the message in chat, not entirely sure though because the last time I looked at this was a few months ago. 

Since I don't know the codebase for CoreProtect well, nor do I know Java well (I'm mostly a web asp.net core developer) I have a few questions before I action this.

1. Why is this enabled even when logging for player chats / commands are disabled. 
2. If I only have block logging enabled, will there be any ramifications for commenting out the PlayerChatListener / PlayerCommandListener
3. What would be a proper fix for this? Does Minecraft have some utility library where we can re-add a hyperlink in a players message?

**Comment by Intelli** [comment]
> I'm guessing this is because CoreProtect is taking the users chat and then copying the message canceling the event and then directly sending the message in chat

CoreProtect does not intercept chat messages. 

Also unable to replicate this issue.

**Comment by braydel** [comment]
It might be patched in newer versions, I've noticed that one of the listeners initializations was changed. It looks like there was changes to the PlayerChatListener, and in result now it is using the PaperChatListener if its available. 

Let me update to the most recent 20.4 version, I was using CoreProtect 20.3 and haven't updated CoreProtect since 1.18 was released.

**Comment by Intelli** [comment]
Listener changes were made in v20.2.

Latest version of CoreProtect w/ latest Paper works fine:
![](http://www.userfolio.com/uploads/Screen-Shot-2022-01-22-19-13-32.71.png)

However, I was actually able to replicate this with a different plugin. I'd advise testing without any other plugins to ensure that CoreProtect is actually the culprit.

**Comment by braydel** [comment]
Intresting... I don't have DarkerNights or TransitTubes. I had a test server with CoreProtect as the only plugin and with my server configuration files and I replicated the issue. Obviously, I tested my server's configuration before I deployed CoreProtect. I have decompiled the CoreProtect jar I have installed on my server, and it looks like the Listener changes are implemented.

Possibly it could be an issue with my paper configuration, but I've also completely reset my paper configuration and copied my old configuration to a test server when I was trying to figure out what was causing this issue.

Let me update this thread when I have more information so you can replicate it and if it continues after I update both paper and CoreProtect. Both CoreProtect and Paper is out of date currently, so hopefully that's the issue. If we potentially can't figure out the issue, are there any ramifications if I just comment out the PlayerChatListener and the PlayerCommandListener?

**Comment by braydel** [comment]
Updating paper / core protect in about 20 minutes, if that doesn't fix the issue, I'll create another test server and see if I can replicate the issue again.

**Comment by braydel** [comment]
Looks like updating worked, maybe it was a paper issue I'm not 100% sure. 

Thanks for the help and work you put into this plugin!
