### ISSUE TITLE
Make co purge availabe for less than 30 days

### ISSUE THREAD

**Issue by bloggy** [PlayPro/CoreProtect#14]
**"You can only purge data older than 30 days".**
In our case this produces way too much data and we need to purge every 14 days at latest.
Do you think you can add an option for that? I see no reason why not make this configurable to less than 30 days.

**Comment by Intelli** [comment]
Newer data can be purged if the command is ran from the console.

The in-game command is restricted to prevent abuse by moderators. Running the command from the console is the recommended method.
