### ISSUE TITLE
Console Errors on server startup.

### ISSUE THREAD

**Issue by BboyZeroOne** [PlayPro/CoreProtect#140]
Currently using CoreProtect 20.4. and Paper 1.18.1

https://pastebin.com/FimGgdJz

Please do take a look, thanks you!

**Comment by vacla** [comment]
@BboyZeroOne there is nothing CoreProtect like error in that log

**Comment by Intelli** [comment]
Those errors aren't from CoreProtect: https://bugs.mojang.com/browse/MC-227945
