### ISSUE TITLE
Radius Ranges

### ISSUE THREAD

**Issue by 7hatGuyAJ** [PlayPro/CoreProtect#148]
It would be nice if we could define a max y level when doing things like diamond ore break lookups on busy servers so we can attempt to filter out those players that obtain the ore using silk touch in order to use fortune on them when they return to their base.

**Comment by Intelli** [comment]
You can already use `r:0x0x0` (x/y/z)

You can also specify a location with `c:0,0,0`.

E.g. if you’re at x50/z244, you should be able to do something like this for a radius lookup on lower y levels:

`co l c:50,0,244 r:50x10x50`

**Comment by 7hatGuyAJ** [comment]
I would like to negate the x and z cords how would I apply that to a global lookup with a "only check below y40"
/co l b:deepslate_diamond_ore,diamond_ore t:2d a:-block r:global

**Comment by 7hatGuyAJ** [comment]
I don't see a way to specify a max y level on a global lookup so I feel my Feature Request is a valid one and not a question unless I'm missing something? Granted I could have probably worded my initial comment better.

**Comment by Intelli** [comment]
"Global" radiuses are unsupported, as the query overwhelms large databases.
