### ISSUE TITLE
1.14 players chest being emptied

### ISSUE THREAD

**Issue by cheesepufftyler** [PlayPro/CoreProtect#15]
Chest are being completely emptied out of no where. it happened when i updated from the 1.13 to the 1.14 version of CO.  co inspect tells me that it got removed most of the time but the players never removed it. some chest say the last thing was something added to it.

**Comment by Intelli** [comment]
Please ensure you're using CoreProtect 2.17.0, and provide steps for replicating the issue you're experiencing.

Please also provide screenshots showing the problem.

**Comment by cheesepufftyler** [comment]
Im for sure im on CO 2.17.0. im not sure how to replicate that issue. it may be happening on a reload or server crash. im not sure tho. provided photos of chest that are logged incorrectly and 1 that got emptied. i managed to save one by rolling it back and restoring it and it placed the items back in. I tried on the other chest but no luck.



![Screenshot (7)](https://user-images.githubusercontent.com/19861859/57573662-089bf400-73f9-11e9-8896-36c7604bb25a.png)
![Screenshot (5)](https://user-images.githubusercontent.com/19861859/57573636-a3e09980-73f8-11e9-80aa-d9a8b1e5c5a2.png)
![Screenshot (6)](https://user-images.githubusercontent.com/19861859/57573637-a4793000-73f8-11e9-8b36-3a1f22b5ddf9.png)
![Screenshot (1)](https://user-images.githubusercontent.com/19861859/57573589-0dac7380-73f8-11e9-922e-47525e3fcbbc.png)
![Screenshot (3)](https://user-images.githubusercontent.com/19861859/57573590-0dac7380-73f8-11e9-8fee-5fb0263da593.png)
![Screenshot (4)](https://user-images.githubusercontent.com/19861859/57573591-0dac7380-73f8-11e9-83a9-7e1a25f2f06a.png)

**Comment by Intelli** [comment]
If the CoreProtect data is missing for a chest, it means it was likely removed from the database.

Data can be removed from the database by using the "/co purge" command. Please ensure you've restricted access to this command, to ensure no users other than yourself can run this command.

**Comment by cheesepufftyler** [comment]
no users can do this command. this command was not used

**Comment by Xeyame** [comment]
can't replicate, are you 100% sure its not another plugin doing this?

**Comment by Intelli** [comment]
If chests are randomly being wiped, that's not a CoreProtect issue.
