### ISSUE TITLE
DB Question entity world location

### ISSUE THREAD

**Issue by LogGits** [PlayPro/CoreProtect#157]
Was just wondering if there is a way via sql to determine what world the co_entity logs are from? I want to purge a specific world from a before a certain date and I noticed the co_entity was in blob form. Any ideas how I can potentially do this?

**Comment by jarekt** [comment]
co_entity logs only nbt data of a given entity. If you want to know more, like who killed it or the world id, you need to join the entity table with the block table (where action type = 3 - thats the action type for kill if I remember corectly) (on time)
