### ISSUE TITLE
Issue in log of villager trades

### ISSUE THREAD

**Issue by Doc94** [PlayPro/CoreProtect#165]
i currently updated to last version but has a random error in a few trades related to InventoryClickEvent.
![image](https://user-images.githubusercontent.com/3602279/157315807-765ad1ab-7db9-44e3-9eb8-afa5a96057f3.png)

Plugins: ConterCraft, ConterSubsHelper, CoreProtect, gProtector, LibsDisguises, LuckPerms, PlugManX (PlugMan), ProtocolLib, SentryIntegration, spark, WorldEdit
Version: Paper version git-Paper-235 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e0b3f3f)

**Comment by Intelli** [comment]
Please provide steps to replicate.

**Comment by Doc94** [comment]
> Please provide steps to replicate.

i test and this happen with a custom wandering trader, but also i test and happen with any wandering trader.

https://user-images.githubusercontent.com/3602279/157319635-596c6be3-a992-4ba3-8274-ee2c5e6b25f8.mp4

**Comment by Intelli** [comment]
Fixed in https://github.com/PlayPro/CoreProtect/commit/975a030ebef624685d04ac5ee1be2f384dc59e1b

**Comment by Doc94** [comment]
Thanks, looks fixed by then close.
