### ISSUE TITLE
Rollbacks leaving behind blocks (even while they should be rolled back)

### ISSUE THREAD

**Issue by MC-MrBirdy** [PlayPro/CoreProtect#175]
**Issue:**
In most cases blocks are left behind when doing a rollback.
Even while using something like time:900w.
Block that are left behind show as that they should be rolled back.

**Using:**
- CoreProtect v21.1
- Paper #265 (and below)
- Vanilla 1.18.2
- No other plugins

**Command example:** /co rollback radius:100 time:900w
**Screenshots:** https://drive.google.com/drive/folders/1H61FaELlBmpYZCHeYZAdjJhEV_jUe_CD?usp=sharing
**Note:** The issue seems to be consistent.

**Comment by Intelli** [comment]
As you say the issue is consistent, are you able to provide exact steps to replicate the issue?

If not, would you be able to provide me a copy of your server files to attempt to replicate the issue? (Intelli#0001 on Discord)

**Comment by MC-MrBirdy** [comment]
Beside rolling back player actions that have occurred from past October (2021) till now.

1. Build a house
2. Roll back the house (/co rb r:100 t:1d)
3. See blocks being left behind

I'll drop you a message on discord to see what I can supply.

**Comment by Intelli** [comment]
Issue confirmed.
