### ISSUE TITLE
return coordinates to  lookup a: inventory, this is useful!

### ISSUE THREAD

**Issue by NotIENJI** [PlayPro/CoreProtect#177]
in previous versions it was possible to view the coordinates in the inventory actions, now this feature has been removed. I would like to see her in the next updates, she was really useful.
![image](https://user-images.githubusercontent.com/102028245/159245409-05c93fe7-a6ba-431f-baad-abb693b7ac3a.png)

**Comment by Intelli** [comment]
Duplicate of #178
