### ISSUE TITLE
CoreProtect PaperInterface null

### ISSUE THREAD

**Issue by vacla** [PlayPro/CoreProtect#183]
When I ran for the first time CoreProtect. I had an issue that the PaperInterface was null, i thought this was because I had a fault in my script when deving that caused it but ever since i ran the next time the paperinterface always is correctly initialised.

Someone recently in the Discord had the same issue: https://discord.com/channels/348680641560313868/348680642155773955/956104150284926987
Logs:
[2022-03-13-2.log](https://github.com/PlayPro/CoreProtect/files/8334929/2022-03-13-2.log)

**Comment by Intelli** [comment]
Fixed in https://github.com/PlayPro/CoreProtect/commit/acdfb3515b613d0690b678ff7bc8594616d1e471
