### ISSUE TITLE
Plugin sometimes removes itself. [Bug]

### ISSUE THREAD

**Issue by FilipeeX** [PlayPro/CoreProtect#186]
### Issue (Bug)
A while ago, CoreProtect plugin just **disappeared from plugins folder**, again. I have absolutely no idea why, but CoreProtect just keeps removing itself from plugins folder and nobody knows why.

### Theory Behing It
There is one theory tough: Some of my server developers were saying that it probably can happens when the plugin update is released & plugin tries to auto update itself, so it tries to download the newest .jar version from internet and removes itself, however it might have some problems with downloading it, another thing that kinda confirms this theory, is that **it often happens right after a update is released** and server is restarted.

### Our View of the Thing
I don't really know, nobody does. We often don't take notice immediately, but after a while we just realize it and download the newest version into the plugins folder. It happens only with CoreProtect, no other plugin. Can't tell you if it's a server problem, because i honestly have no idea.. I can't really produce this bug either but i'll let you know if it happens again & when it happened.

### Other Info
Other probably useful info: (don't really know if it is useful in any way, but here it is anyway)
We are running *paper spigot*, the newest *1.18.1* version. Current version of *CoreProtect* on our server right now is the newest released. This is happening for about *3 months* now.

**Comment by Intelli** [comment]
What server host are you using?

**Comment by FilipeeX** [comment]
> What server host are you using?

I'm using a local Czechoslovakian hosting, hicoria.com.

**Comment by Intelli** [comment]
Hicoria is known for engaging in dishonest business practices, such as deleting plugins upon startup and preventing certain plugins from running unless customers upgrade to a higher plan.

Switching to a new server host is strongly recommended to resolve any issues you're experiencing. A number of alternative hosting options can be found at https://admincraft.co/marketplace/

**Comment by FilipeeX** [comment]
Interesting, i've never heard of that before. Many people have recommended me to switch, but it's nearly impossible because no other hostings have proper SMS & PSC payments for Slovakia and Czechia + i already have like $50 in there in the form of credits, so not very easy to switch, but we're considering everything.

Anyways, thanks for your time, Filip - Owner of OpSurvival.

**Comment by Intelli** [comment]
The easiest temporary fix would likely be renaming the JAR file so it doesn't mention CoreProtect.

For example: `plugin.jar`.

Cheers!
