### ISSUE TITLE
Add Japanese translation

### ISSUE THREAD

**Issue by LZMAShili** [PlayPro/CoreProtect#194]
Is your feature request related to a problem? Please describe.
A Japanese translation was needed.
I did the translation.

Describe the solution you'd like
Addition of ja.yml that I prepared
[ja.txt](https://github.com/PlayPro/CoreProtect/files/8357936/ja.txt)

Describe alternatives you've considered
Addition of Japanese translations by someone other than myself

Additional context
Notiong

**Comment by vacla** [comment]
@LZMAShili you can make a PR with the changes you made to the current file.

**Comment by LZMAShili** [comment]
> @LZMAShili you can make a PR with the changes you made to the current file.

I'm sorry, I can translate, but I'm not used to using GitHub. If you can do me a favor, could you give me a PR instead?
