### ISSUE TITLE
FastAsyncWorldEdit hook

### ISSUE THREAD

**Issue by LuluxClient** [PlayPro/CoreProtect#196]
Hey I saw the FastAsyncWorldEdit hook is no longer working. I'm on 1.18.2 Java 17 CoreProtect 21.2 and Fawe 2.1.1 build 134
Command used: /co rollback t:15m r:#worldedit

**Comment by Intelli** [comment]
Tested #134, radius selections & logging are both working.

![image](https://user-images.githubusercontent.com/6790859/160500134-0f655176-5d9c-421f-85cf-af03c71f2e3f.png)

**Comment by LuluxClient** [comment]
Could you provide me with your FAWE version and command you used since the
command on the wiki didn’t work for a selection a did and //cutted it

**Comment by Intelli** [comment]
FastAsyncWorldEdit-134

`/co rollback t:15m r:#worldedit`

**Comment by LuluxClient** [comment]
I’ll try that tomorrow (same command) if issue is resolved I’ll close the
issue. Thanks for the answer. Also what are the changes between the donator
version of coreprotect ?
