### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by Devan-Kerman** [PlayPro/CoreProtect#20]
is the Artistic License 2.0 applied to the plugin itself, am I able to decompile CoreProtect and port it to a different platform? (or obtain the source)

**Comment by Intelli** [comment]
The license applies to the code in this repository. Redistributing decompiled code is not permitted at the present time. 

Decompiling for personal use however is permitted.

**Comment by Devan-Kerman** [comment]
ok thank you
