### ISSUE TITLE
org.sqlite.SQLiteException

### ISSUE THREAD

**Issue by FishOwO** [PlayPro/CoreProtect#205]
! [Sat 07:33:22 WARN ] org.sqlite.SQLiteException: [SQLITE_IOERR_FSYNC]  I/O error in the VFS layer while trying to flush previously written content (disk I/O error)
! [Sat 07:33:22 WARN ]     at org.sqlite.core.DB.newSQLException(DB.java:1030)
! [Sat 07:33:22 WARN ]     at org.sqlite.core.DB.newSQLException(DB.java:1042)
! [Sat 07:33:22 WARN ]     at org.sqlite.core.DB.throwex(DB.java:1007)
! [Sat 07:33:22 WARN ]     at org.sqlite.core.NativeDB._exec_utf8(Native Method)
! [Sat 07:33:22 WARN ]     at org.sqlite.core.NativeDB._exec(NativeDB.java:97)
! [Sat 07:33:22 WARN ]     at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:102)
! [Sat 07:33:22 WARN ]     at CoreProtect-21.2.jar//net.coreprotect.database.Database.commitTransaction(Database.java:71)
! [Sat 07:33:22 WARN ]     at CoreProtect-21.2.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:99)
! [Sat 07:33:22 WARN ]     at CoreProtect-21.2.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
! [Sat 07:33:22 WARN ]     at java.base/java.lang.Thread.run(Thread.java:833)
! [Sat 07:33:22 WARN ] org.sqlite.SQLiteException: [SQLITE_IOERR_FSYNC]  I/O error in the VFS layer while trying to flush previously written content (disk I/O error)
! [Sat 07:33:22 WARN ]     at org.sqlite.core.DB.newSQLException(DB.java:1030)
! [Sat 07:33:22 WARN ]     at org.sqlite.core.DB.newSQLException(DB.java:1042)
! [Sat 07:33:22 WARN ]     at org.sqlite.core.DB.throwex(DB.java:1007)
! [Sat 07:33:22 WARN ]     at org.sqlite.core.NativeDB._exec_utf8(Native Method)
! [Sat 07:33:22 WARN ]     at org.sqlite.core.NativeDB._exec(NativeDB.java:97)
! [Sat 07:33:22 WARN ]     at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:102)
 
! [Sat 07:33:22 WARN ]     at CoreProtect-21.2.jar//net.coreprotect.database.Database.commitTransaction(Database.java:71)
! [Sat 07:33:22 WARN ]     at CoreProtect-21.2.jar//net.coreprotect.consumer.process.Process.commit(Process.java:296)
! [Sat 07:33:22 WARN ]     at CoreProtect-21.2.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:248)
! [Sat 07:33:22 WARN ]     at CoreProtect-21.2.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
! [Sat 07:33:22 WARN ]     at java.base/java.lang.Thread.run(Thread.java:833)

I'm hosting this server on my pc, not on a host.
System Info: Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-107-generic x86_64)
Paper 1.18.2

Is using mysql better?

**Comment by Intelli** [comment]
https://www.sqlite.org/rescode.html#ioerr_fsync

Error doesn't pertain to CoreProtect code.
