### ISSUE TITLE
Suggestion: Being able to search above/below certain Y lvl

### ISSUE THREAD

**Issue by Birkirrr** [PlayPro/CoreProtect#206]
Lets say when checking diamond ores mined logs, being able to lookup diamond ores mined below y: 16 (Natural generated diamonds can only spawn below y:16) would make my life and the other admins life much easier as half the server mines all their diamonds with silk touch, and then mines them again above ground at their base, doubling the amount of logs of diamond ores mined logs.

**Comment by Birkirrr** [comment]
Example:
/co lookup action: -block include: deepslate_diamond_ore, diamond_ore y:16 time: 1d

Then it would only show deepslate diamond ores and diamond ores mined below y: 16

**Comment by Intelli** [comment]
Duplicate of #148
