### ISSUE TITLE
error with SQLite

### ISSUE THREAD

**Issue by mashkhale** [PlayPro/CoreProtect#214]
few day ago my console start to give this spam error of coreprotect

[Sat, 30. Apr 2022 17:08:39 EDT WARN] org.sqlite.SQLiteException: [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)
[Sat, 30. Apr 2022 17:08:39 EDT WARN] at org.sqlite.core.DB.newSQLException(DB.java:1012)
[Sat, 30. Apr 2022 17:08:39 EDT WARN] at org.sqlite.core.DB.newSQLException(DB.java:1024)
[Sat, 30. Apr 2022 17:08:39 EDT WARN] at org.sqlite.core.DB.execute(DB.java:866)
[Sat, 30. Apr 2022 17:08:39 EDT WARN] at org.sqlite.core.DB.executeUpdate(DB.java:904)
[Sat, 30. Apr 2022 17:08:39 EDT WARN] at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
[Sat, 30. Apr 2022 17:08:44 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:33)
[Sat, 30. Apr 2022 17:08:44 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:39)
[Sat, 30. Apr 2022 17:08:44 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[Sat, 30. Apr 2022 17:08:44 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:185)
[Sat, 30. Apr 2022 17:08:44 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[Sat, 30. Apr 2022 17:08:44 EDT WARN] at java.base/java.lang.Thread.run(Thread.java:833)
[Sat, 30. Apr 2022 17:08:44 EDT WARN] java.sql.SQLException: statement is not executing
[Sat, 30. Apr 2022 17:08:44 EDT WARN] at org.sqlite.core.CoreStatement.checkOpen(CoreStatement.java:55)
[Sat, 30. Apr 2022 17:08:44 EDT WARN] at org.sqlite.core.CorePreparedStatement.batch(CorePreparedStatement.java:102)
[Sat, 30. Apr 2022 17:08:44 EDT WARN] at org.sqlite.jdbc3.JDBC3PreparedStatement.setInt(JDBC3PreparedStatement.java:323)
[Sat, 30. Apr 2022 17:08:44 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:31)
[Sat, 30. Apr 2022 17:08:44 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:39)
[Sat, 30. Apr 2022 17:08:44 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[Sat, 30. Apr 2022 17:08:44 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:185)
[Sat, 30. Apr 2022 17:08:44 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[Sat, 30. Apr 2022 17:08:49 EDT WARN] at java.base/java.lang.Thread.run(Thread.java:833)
[Sat, 30. Apr 2022 17:08:49 EDT WARN] org.sqlite.SQLiteException: [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)
[Sat, 30. Apr 2022 17:08:49 EDT WARN] at org.sqlite.core.DB.newSQLException(DB.java:1012)
[Sat, 30. Apr 2022 17:08:49 EDT WARN] at org.sqlite.core.DB.newSQLException(DB.java:1024)
[Sat, 30. Apr 2022 17:08:49 EDT WARN] at org.sqlite.core.DB.execute(DB.java:866)
[Sat, 30. Apr 2022 17:08:49 EDT WARN] at org.sqlite.core.DB.executeUpdate(DB.java:904)
[Sat, 30. Apr 2022 17:08:49 EDT WARN] at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
[Sat, 30. Apr 2022 17:08:49 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:33)
[Sat, 30. Apr 2022 17:08:49 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:39)
[Sat, 30. Apr 2022 17:08:49 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[Sat, 30. Apr 2022 17:08:49 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:185)
[Sat, 30. Apr 2022 17:08:49 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[Sat, 30. Apr 2022 17:08:49 EDT WARN] at java.base/java.lang.Thread.run(Thread.java:833)
[Sat, 30. Apr 2022 17:08:49 EDT WARN] org.sqlite.SQLiteException: [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)
[Sat, 30. Apr 2022 17:08:49 EDT WARN] at org.sqlite.core.DB.newSQLException(DB.java:1012)
[Sat, 30. Apr 2022 17:08:49 EDT WARN] at org.sqlite.core.DB.newSQLException(DB.java:1024)
[Sat, 30. Apr 2022 17:08:49 EDT WARN] at org.sqlite.core.DB.execute(DB.java:866)
[Sat, 30. Apr 2022 17:08:54 EDT WARN] at org.sqlite.core.DB.executeUpdate(DB.java:904)
[Sat, 30. Apr 2022 17:08:54 EDT WARN] at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
[Sat, 30. Apr 2022 17:08:54 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:33)
[Sat, 30. Apr 2022 17:08:54 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:39)
[Sat, 30. Apr 2022 17:08:54 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[Sat, 30. Apr 2022 17:08:54 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:185)
[Sat, 30. Apr 2022 17:08:54 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[Sat, 30. Apr 2022 17:08:54 EDT WARN] at java.base/java.lang.Thread.run(Thread.java:833)
[Sat, 30. Apr 2022 17:08:54 EDT WARN] org.sqlite.SQLiteException: [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)
[Sat, 30. Apr 2022 17:08:54 EDT WARN] at org.sqlite.core.DB.newSQLException(DB.java:1012)
[Sat, 30. Apr 2022 17:08:54 EDT WARN] at org.sqlite.core.DB.newSQLException(DB.java:1024)
[Sat, 30. Apr 2022 17:08:54 EDT WARN] at org.sqlite.core.DB.execute(DB.java:866)
[Sat, 30. Apr 2022 17:08:54 EDT WARN] at org.sqlite.core.DB.executeUpdate(DB.java:904)
[Sat, 30. Apr 2022 17:08:54 EDT WARN] at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
[Sat, 30. Apr 2022 17:08:54 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.database.statement.EntityStatement.insert(EntityStatement.java:33)
[Sat, 30. Apr 2022 17:08:54 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.database.logger.EntityKillLogger.log(EntityKillLogger.java:39)
[Sat, 30. Apr 2022 17:08:54 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.consumer.process.EntityKillProcess.process(EntityKillProcess.java:24)
[Sat, 30. Apr 2022 17:08:59 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:185)
[Sat, 30. Apr 2022 17:08:59 EDT WARN] at CoreProtect-20.4.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[Sat, 30. Apr 2022 17:08:59 EDT WARN] at java.base/java.lang.Thread.run(Thread.java:833)
[Sat, 30. Apr 2022 17:08:59 EDT WARN] org.sqlite.SQLiteException: [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)
[Sat, 30. Apr 2022 17:08:59 EDT WARN] at org.sqlite.core.DB.newSQLException(DB.java:1012)
[Sat, 30. Apr 2022 17:08:59 EDT WARN] at org.sqlite.core.DB.newSQLException(DB.java:1024)
[Sat, 30. Apr 2022 17:08:59 EDT WARN] at org.sqlite.core.DB.execute(DB.java:866)
[Sat, 30. Apr 2022 17:08:59 EDT WARN] at org.sqlite.core.DB.executeUpdate(DB.java:904)
[Sat, 30. Apr 2022 17:08:59 EDT WARN] at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)

i would like to know what to do and maybe how bc i dont know to much of this things about coding 🥺

**Comment by Intelli** [comment]
> The database disk image is malformed (database disk image is malformed)

Your `database.db` file is corrupt. You can either attempt a purge to repair it, or delete the file to start a new database.
