### ISSUE TITLE
Log player death

### ISSUE THREAD

**Issue by Leeo97one** [PlayPro/CoreProtect#216]
I think it could be useful to log player death and be able to rollback it (i.e. inventory and exp).

**Comment by Intelli** [comment]
Player deaths are already logged (death under a:kill, drops upon death under a:inventory)

**Comment by Lotzyprod** [comment]
Let's say a player killed me. I didn’t remember the coordinates, the nickname either, the question is how can I find the one who killed me, if logging occurs only on behalf of the killer?
That is, it will be logged that %n% killed me, but it will not be logged that I died from %n%
