### ISSUE TITLE
Suggestion: Command tracking

### ISSUE THREAD

**Issue by DonCordeleone** [PlayPro/CoreProtect#225]
Please consider adding a search function for /co l <user> a:command as in searching for a specific command used. 

Ex: /co l <user> a:command command:/hi

That would bring up only those commands used by the player within any other parameters such as time or radius. Or an exclusion would work great too such as: 

/co l <user> a:command exclude:/hi, /hello, /co l, /co i, /spawn that would display all commands excluding the ones in the exclude parameter.

**Comment by Intelli** [comment]
Duplicate of #159
