### ISSUE TITLE
Vanished players are exposed.

### ISSUE THREAD

**Issue by mrfloris** [PlayPro/CoreProtect#226]
Hey, it looks that by default vanished players are exposed through core protect to all players, even if they don't have the permission node to use the lookup tool. 
```
co l u:
```
<img width="471" alt="Screenshot 2022-06-06 at 11 52 17" src="https://user-images.githubusercontent.com/28841349/172138862-5a17520d-e8d5-4b50-90ad-ad60fdd0fc9c.png">

```
> ver
[11:57:36 INFO]: Checking version, please wait...
[11:57:36 INFO]: This server is running Paper version git-Paper-378 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 4b27254)
You are running the latest version
Previous version: git-Paper-375 (MC: 1.18.2)
> ver CoreProtect
[11:57:39 INFO]: CoreProtect version 21.2
[11:57:39 INFO]: Provides block protection for your server.

[11:57:39 INFO]: Website: http://coreprotect.net
[11:57:39 INFO]: Author: Intelli
```

**Comment by mrfloris** [comment]
> omg, autocompletion w/o permission, sounds like backdoor to the server /: Hope this will be fixed quickly.. but looking at a bunch of other unanswered issues, it's hard to hope ):

Please don't troll github, either contribute something constructive or keep your poor assumptions and accusations to yourself.

**Comment by Firetop** [comment]
> > omg, autocompletion w/o permission, sounds like backdoor to the server /: Hope this will be fixed quickly.. but looking at a bunch of other unanswered issues, it's hard to hope ):
> 
> Please don't troll github, either contribute something constructive or keep your poor assumptions and accusations to yourself.

What Vanishing Plugin are you using? 
EssentialsX? VanishNoPacket? Or SuperVanish? 

Just curious if this is the same issue affecting me.
Thanks!

**Comment by Intelli** [comment]
I'll change tab completion to be disabled if a user doesn't have lookup permissions.
