### ISSUE TITLE
[Config Suggestion] Exclude certain commands from being registered

### ISSUE THREAD

**Issue by MithrandirCraft** [PlayPro/CoreProtect#23]
So there's currently an option to disable the registry of all commands, but all I want is for authme's commands not to get registred, since whoever has access can see passwords which is a bit over the top / unnecesary, all other commands are fine.

**Comment by Intelli** [comment]
For feedback, suggestions, or support, please go here: https://dev.bukkit.org/projects/coreprotect/issues

We also have a Discord server, located at https://discord.gg/b4DZ4jy
