### ISSUE TITLE
Pastes made in FastAsyncWorldEdit are not logging in CoreProtect

### ISSUE THREAD

**Issue by book000** [PlayPro/CoreProtect#234]
Hello. This is a bug report or improvement request for the ability to logging changes in FastAsyncWorldEdit to CoreProtect.

I am using FastAsyncWorldEdit and CoreProtect. I copied the block and pasting the copy does not logging it in CoreProtect.
A video of this phenomenon actually occurring was taken and is attached below.

https://user-images.githubusercontent.com/8929706/173679825-b7f7f246-d011-4269-a584-2318a1bab0b6.mp4

## Environments

- Windows 10 21H2 (Build 19044.1706)
- openjdk 17.0.3 2022-04-19 LTS
- PaperMC 1.18.2 385
- CoreProtect [v21.2](https://github.com/PlayPro/CoreProtect/releases/tag/v21.2)
- FastAsyncWorldEdit [v2.3.1-205](https://ci.athion.net/job/FastAsyncWorldEdit/205/)

## Step for reproduce

1. Build a PaperMC server and add the CoreProtect and FastAsyncWorldEdit jar files to the plugins.
2. Modify the configuration file with reference to the following [#Configuration](#Configuration).
3. Login to the server and grant yourself an operator.
4. Place any block. (And check that there is an placed record for the blocks placed)
6. Copy the placed block: `//copy`
7. Paste what you just copied elsewhere: `//paste`
8. No error logs are output to the server log and no placed logs are logged in CoreProtect.

### `plugins/FastAsyncWorldEdit/config.yml`

```diff
--- config.yml.old      2022-06-15 04:44:06.753611000 +0900
+++ config.yml  2022-06-15 04:46:38.612349700 +0900
@@ -89,7 +89,7 @@
   # Don't bug console when these plugins slow down WorldEdit operations
   #  - You'll see a message in console or ingame if you need to change this option
   allowed-plugins:
-  - "com.example.ExamplePlugin"
+  - "net.coreprotect.worldedit.CoreProtectLogger"
   # Should debug messages be sent when third party extents are used?
   debug: true
```

### `server.properties`

This edit is set to facilitate checking the operation and is not required for reproduction. (The default setting is fine)

```properties
#Minecraft server properties
gamemode=creative
difficulty=peaceful
level-type=flat
```

I look forward to your reply.

**Comment by book000** [comment]
Yes. The placed (pastes) logs appear to be logged normally in the following environments:

- PaperMC 1.18.2 385
- CoreProtect [v21.2](https://github.com/PlayPro/CoreProtect/releases/tag/v21.2)
- WorldEdit for Bukkit [v7.2.10 (1.13.2 - 1.18.2)](https://dev.bukkit.org/projects/worldedit/files/3697296)

And here is a video of the tests:

https://user-images.githubusercontent.com/8929706/175603646-df83beab-703d-4c8d-af4a-3fe9c001ea3d.mp4

Thus, it appears to be recorded in standard WorldEdit but not in AsyncWorldEdit.

**Comment by Intelli** [comment]
Please test with FAWE 2.4.0

**Comment by book000** [comment]
Thanks to reply. I have tested with FastAsyncWorldEdit 2.4.0 and 2.4.1 and there is no log of pasting.

## Environments

- openjdk 17.0.3 2022-04-19 LTS (Corretto-17.0.3.6.1)
- PaperMC 1.18.2-385 (Also tried with the latest version: 1.8.2-386)
- CoreProtect [v21.2](https://github.com/PlayPro/CoreProtect/releases/tag/v21.2)
- FastAsyncWorldEdit [2.4.1-238](https://ci.athion.net/job/FastAsyncWorldEdit/238/) (Also tried with [2.4.0-235](https://ci.athion.net/job/FastAsyncWorldEdit/235/))

## Video

https://user-images.githubusercontent.com/8929706/176321704-eee1c0bb-efe2-489d-9c6e-b1a7898eaa29.mp4

(I have tested in an environment with Watson Mod and other mods, so some of the rendering is different, but there is no problem with the server settings.)

**Comment by Intelli** [comment]
I likely won’t be spending time on this myself, but someone else is welcome to take a stab at it if they want.

**Comment by katorly** [comment]
CoreProtect also doesn't log changes made by GoPaint, GoBrush and VoxelSniper, which rely on FastAsyncWorldEdit.

**Comment by Landy005** [comment]
Literally who uses worldedit these days everyone is using fawe, what's the point of worldedit support if its not for fawe?
