### ISSUE TITLE
[1.19] Rolled back frogs don't preserve their variant

### ISSUE THREAD

**Issue by Podgorica** [PlayPro/CoreProtect#235]
When rolling back a frog that has been killed it respawns as the variant for the temperature of the current biome, rather than the variant it was before death.

`/summon frog ~ ~ ~ {variant:cold}` while in a desert biome
![image](https://user-images.githubusercontent.com/70448311/173930447-87d31c61-e0e1-459d-8b2f-d8f4a1a3c7d0.png)

After killing and rolling back, it comes back as a warm frog.
![image](https://user-images.githubusercontent.com/70448311/173930425-bebd7503-bc39-4a6d-b905-4245d2889707.png)

**Comment by Intelli** [comment]
Implemented in #239
