### ISSUE TITLE
[Suggestion] Option to not log InventoryMoveEvent items if they have no metadata

### ISSUE THREAD

**Issue by HexedHero** [PlayPro/CoreProtect#24]
Add an option to only log items in the InventoryMoveEvent if the item has any metadata such as a custom name, lore, enchantments etc.

Recently my CoreProtect purges have been taking over 2 hours and almost 75% of that is taken up by processing the container data so I checked the database and indeed pretty much a lot of the information is items transferred with hoppers and almost all of them are useless items like mob drops not anything special.

**Comment by Intelli** [comment]
Feature added in v20.0

To enable, set `hopper-filter-meta: true` in the config.yml file
