### ISSUE TITLE
[Don't kill me] Fabric port please? :-(

### ISSUE THREAD

**Issue by Sebas-Re** [PlayPro/CoreProtect#242]
Couldn't find a straight answer about this other than people suggesting to "Use Ledger"...

I would like to suggest a fabric port of this incredible plugin, if it's not asking much :( I know Ledger exists and it's kinda the only logger available for Fabric, but CoreProtect is simply far superior than that crap (it even stops logging by itself for some reason, so I sometimes have like a 5hr gap between logs, which is not ideal if you're trying to protect your server from getting griefed).

Look at this...look at this!
![image](https://user-images.githubusercontent.com/32151264/175534671-c6ac0f9e-e346-4f03-a2ee-84f836aeb61b.png)
It's almost pitiful to look at, doesn't even log item pick ups or drops, which is a must for this type of mod (already suggested them to add this action, among others, months ago and got literally no response).

I've been using CoreProtect for literal years, so going from this jaw-dropping plugin to... this... it's just.. sad, to say the least...

I bet if you people could port this plugin into a fabric mod (I'm not sure who hard that could be, so hopefully I'm not asking for the impossible 😔) , it will surely overcome Ledger downloads in no time :D <3

**Comment by Intelli** [comment]
Duplicate of #37

**Comment by Sebas-Re** [comment]
.....guess not....

**Comment by Intelli** [comment]
CoreProtect for Fabric is now available at https://coreprotect.net/fabric

**Comment by DereC4** [comment]
W!
