### ISSUE TITLE
shorter maxLifetime value (MySQL)

### ISSUE THREAD

**Issue by TheDiVaZo** [PlayPro/CoreProtect#243]
[net.coreprotect.hikari.pool.PoolBase] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@49626958 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value

in the database settings, I cannot increase the value of wait_timeout (value: 60, Hosting does not give the permission), so I would like to find out how I can decrease maxLifetime. Can I change it via config?

**Comment by Intelli** [comment]
Duplicate of #199
