### ISSUE TITLE
Add option to prevent logging blocks placed by dispensers

### ISSUE THREAD

**Issue by molor** [PlayPro/CoreProtect#250]
In our case, this can greatly reduce number of useless writes to DB due to automated moss farms based on lava, water and pistons. 
Some of our players uses 1-3 of this farms and average number of pages during `/co inspect` **on each block** is about **10k** (dispenser placed, water broke, dispenser placed, water broke, ...)

Thanks!

**Comment by Podgorica** [comment]
See the "Disable Logging" section of the [configuration documentation](https://docs.coreprotect.net/config/). 

This is already possible, you need to create a `blacklist.txt` file and add `#dispenser` to it.

**Comment by molor** [comment]
I'm completely forgot about blacklist :/
Thanks, @Podgorica
