### ISSUE TITLE
Enable wordedit integration

### ISSUE THREAD

**Issue by sujyrokimora** [PlayPro/CoreProtect#251]
![image](https://user-images.githubusercontent.com/37046592/178017379-19b6332a-7a77-4161-a2e6-96fd76611ab5.png)
![image](https://user-images.githubusercontent.com/37046592/178017657-1ba924b1-b02f-43a9-936d-de018c3d73d2.png)
Its enabled but shows disabled, any idea how to fix?

**Comment by vacla** [comment]
This likely duplicate of #245 without almost no info to know what the errors are in your logs

**Comment by sujyrokimora** [comment]
![image](https://user-images.githubusercontent.com/37046592/178020632-0203debc-0c10-4879-b764-7ac69e3725da.png)
only thing that shows up

**Comment by sujyrokimora** [comment]
Do i need to compile this myself or there is a download link?

**Comment by Intelli** [comment]
Duplicate of #245
