### ISSUE TITLE
Coreprotect general

### ISSUE THREAD

**Issue by Redblazer27** [PlayPro/CoreProtect#258]
Hello. I have been using coreprotect for a short time and in our vanilla there have been some cases of grief to restore them I used rollback but with the item frames andthe items in the chest It didn't work. so I wanted to know what Is the command to make that happen. also I would like to know if there is a command to return inventory to a player.

**Comment by CommandoEchino** [comment]
Re: your first question, I have never been able to get item frames to roll back properly. It's the one part of CoreProtect I can't get to work. However, chests should definitely rollback, so I'm not sure what's up with that. What command are you using?

For your second question, there isn't a command to do that currently. I would recommend installing [Inventory Restore Plus](https://www.spigotmc.org/resources/inventory-rollback-plus-1-8-1-19-x.85811/). 

It's a little difficult to use but it is a great solution in the interim until inventory rollback is added to CoreProtect (if it ever ends up happening).

**Comment by creepertamer8** [comment]
> Re: your first question, I have never been able to get item frames to roll back properly. It's the one part of CoreProtect I can't get to work. However, chests should definitely rollback, so I'm not sure what's up with that. What command are you using?
> 
> For your second question, there isn't a command to do that currently. I would recommend installing [Inventory Restore Plus](https://www.spigotmc.org/resources/inventory-rollback-plus-1-8-1-19-x.85811/).
> 
> It's a little difficult to use but it is a great solution in the interim until inventory rollback is added to CoreProtect (if it ever ends up happening).

Hey, I'm just a bit confused why you say inventory rollback has not been added.. in the /co rollback command, inventory is one of the options under the action parameter, and in the wiki it lists a couple example commands to rollback an inventory. however, when I try to actually do this in game, it says 'This action is not supported by the command.' So is it like a possible feature they just haven't fully implemented yet?

**Comment by CommandoEchino** [comment]
> Hey, I'm just a bit confused why you say inventory rollback has not been added.. in the /co rollback command, inventory is one of the options under the action parameter, and in the wiki it lists a couple example commands to rollback an inventory. however, when I try to actually do this in game, it says 'This action is not supported by the command.' So is it like a possible feature they just haven't fully implemented yet?

It seems like it, yeah. My theory (based on nothing but some extremely base-level coding experience with Javascript) is that the only reason "inventory" is included in that the devs are reusing the code for the `/co lookup` command, which includes "inventory" as an option for the syntax. Instead of removing that autofill suggestion for `/co rollback` and `/co restore`, they just kept it in and band-aided the issue by making an error appear when you try to execute those commands with that invalid syntax.

But that's just a theory..._a code theory._

**Comment by Intelli** [comment]
Inventory rollback support and item frame container transaction support were both added in CoreProtect v21.
