### ISSUE TITLE
Move the `donation-key` and database fields into their own file

### ISSUE THREAD

**Issue by MilesBHuff** [PlayPro/CoreProtect#266]
My Minecraft server, [Settlescape](https://github.com/SettleScape/server), has its configs available on GitHub.  This is used both as a handy way to track and deploy changes, and as a way for our playerbase to contribute to the project.
Sometimes, though, there are settings that aren't appropriate for a public GitHub repo:  API keys, license keys, database passwords, and more.

When these sensitive settings are included in the same files as the non-sensitive settings, I am forced into an awkward situation where I have uncommitable changes in version-controlled files.  It would be much nicer if these sensitive settings were placed into their own separate file, as I could then `.gitignore` it.
At present, pushing changes to one of these limbo configs guarantees a merge conflict on the server during the subsequent pull.  And when working on anything in the repo, I have to be very careful to not accidentally commit any sensitive settings.  Neither of these is ideal.

**I am a donor.**

**Comment by Intelli** [comment]
You can already create per-world files without database or donation key information: https://docs.coreprotect.net/config/#per-world-configuration

**Comment by MilesBHuff** [comment]
While that is good to know, it comes with the caveat that I then have to duplicate our config for each world, instead of configuring things from the central config.

**Comment by MilesBHuff** [comment]
Bump.  I actually donated $6 specifically to fund this small change.  I know that's no guarantee that a particular feature will or won't be added, but please seriously consider this one.

**Comment by MilesBHuff** [comment]
Bump.
