### ISSUE TITLE
Concrete Powder Being Turned Into Concrete Is Not Logged

### ISSUE THREAD

**Issue by CommandoEchino** [PlayPro/CoreProtect#268]
Hello. I recently I had an issue where one of the players on my server griefed a road system made of concrete powder by pouring water buckets on it and turning it all to concrete. 

I was unable to roll back the damage done due to the fact that CoreProtect does not log these conversions. Instead, it logged `#water placed water` a hundred times, which is completely useless IMO but I digress.

I think it is really important that these actions be logged so that players cannot irreparably grief structures or builds made of concrete powder. I was only able to fix the road system by installing and using WorldEdit, but it was very difficult and tedious compared to just using CoreProtect.

**Comment by Intelli** [comment]
Unable to replicate with CoreProtect v21.2 on Paper-1.19.2-307.

<img width="565" alt="image" src="https://user-images.githubusercontent.com/6790859/206322038-091b7eb9-2c32-4e9c-badd-f2c7db1b05e2.png">
