### ISSUE TITLE
Massive Lag spike during Database.getConnection()

### ISSUE THREAD

**Issue by SirKillian** [PlayPro/CoreProtect#270]
Every so often CoreProtect has massive lag issues when making connections.

![8e2cau0n8krcxbfa](https://user-images.githubusercontent.com/19877696/182209671-47ee80b1-fd40-4c96-a085-d9d07ebdcbbd.png)

This is caused by sleeping on the main thread.
https://github.com/PlayPro/CoreProtect/blob/b450f4d05a87f8f50fd2e8958c374adea9698b9a/src/main/java/net/coreprotect/database/Database.java#L164

**Comment by Intelli** [comment]
That's an API call, meaning some other plugin is running it on the main thread.
