### ISSUE TITLE
no update 1.19.1

### ISSUE THREAD

**Issue by DimaSergeew** [PlayPro/CoreProtect#271]
NO update!!!!

**Comment by vacla** [comment]
@DimaSergeew have you tried using v21.2 already?

**Comment by DimaSergeew** [comment]
> @DimaSergeew have you tried using v21.2 already?

Yes, error 1.19.1

**Comment by vacla** [comment]
@DimaSergeew can you show what the error is, otherwise we cant help you further.

**Comment by arima0k** [comment]
Coreprotect works out of the box with 1.19.1.

Unnecessary issue.

**Comment by NoaHimesaka1873** [comment]
![Screenshot 2022-08-05 at 11 31 50 PM](https://user-images.githubusercontent.com/39993457/183098862-8503e69c-3cf2-4a66-8b45-e12ece253fdf.png)
Well, it just works.
