### ISSUE TITLE
Logging WorldEdit

### ISSUE THREAD

**Issue by StonFlip** [PlayPro/CoreProtect#276]
instead of the original worldedit, I use the more convenient FAWE (FastAsyncWorldEdit)
and coreprotect does not log FAWE actions
Could you add FAWE support in future updates?

**Comment by emielderckx** [comment]
You could have looked at earlier issues: #234 
(Also FAWE can corrupt your world.)

**Comment by vacla** [comment]
I'm not sure if it is still needed but have you tried putting Blockshub on the server also?

**Comment by StonFlip** [comment]
> You could have looked at earlier issues: #234 (Also FAWE can corrupt your world.)

As I understand it, it says to use an older version 2.4.1, but I'm using the latest version from the site and is it possible to fix this without changing the FAWE version?

**Comment by book000** [comment]
If you don't know...

To use FastAsyncWorldEdit and CoreProtect to log block edits with set commands, etc., FastAsyncWorldEdit settings must be changed as follows:

`plugins/FastAsyncWorldEdit/config.yml`

```diff
--- config.yml.old      2022-06-15 04:44:06.753611000 +0900
+++ config.yml  2022-06-15 04:46:38.612349700 +0900
@@ -89,7 +89,7 @@
   # Don't bug console when these plugins slow down WorldEdit operations
   #  - You'll see a message in console or ingame if you need to change this option
   allowed-plugins:
-  - "com.example.ExamplePlugin"
+  - "net.coreprotect.worldedit.CoreProtectLogger"
   # Should debug messages be sent when third party extents are used?
   debug: true
```

However, at this time there is a problem that even with this method, the results of copy/paste edits are not logged.
According to [Intelli](https://github.com/Intelli), [if you need to resolve this issue, please create a pull request](https://github.com/PlayPro/CoreProtect/issues/234#issuecomment-1182557570).

- Reference: #234
