### ISSUE TITLE
permisions

### ISSUE THREAD

**Issue by dilowlok187** [PlayPro/CoreProtect#279]
hey , how do i change permision ? i want coreprotect to be usable for all players on mine server

**Comment by emielderckx** [comment]
You can use a plugin like https://luckperms.net/ to set the permissions. If you still need help join the [Discord](https://discord.gg/b4DZ4jy) or look at the [docs](https://docs.coreprotect.net/).

GitHub issues are for bugs, feature requests etc, not questions.
