### ISSUE TITLE
Bug: Coordinate-Based Lookups Via Console

### ISSUE THREAD

**Issue by TheMattVid** [PlayPro/CoreProtect#280]
I have this command that I can use as a player to look at container transactions at a specific coordinate in-game:
/co lookup time:1w c:12085,111,4090 action:container radius:0

However, if I run that same command in the console, I get this error message:
"CoreProtect - Please specify a user or radius to lookup."

**Comment by vacla** [comment]
@TheMattVid try to use a radius bigger then 0

**Comment by TheMattVid** [comment]
> @TheMattVid try to use a radius bigger then 0

Same error message in console when using radius 10 or 100. Still works in-game.

**Comment by vacla** [comment]
Which coreprotect version do you use?

**Comment by TheMattVid** [comment]
> Which coreprotect version do you use?

I am on v21.2

**Comment by Intelli** [comment]
You didn’t specify a world.

E.g. `r:#world r:0`

**Comment by TheMattVid** [comment]
> You didn’t specify a world.

I facepalmed myself. Thanks!
