### ISSUE TITLE
Suggestion: Filter data when logging

### ISSUE THREAD

**Issue by XXY233** [PlayPro/CoreProtect#285]
In some survival type Minecraft servers, players usually build farms, which will cause a lot of useless duplicate data to be logged in the coreprotect database.
   
   

![farms](https://user-images.githubusercontent.com/46647646/188259202-186eaf1e-666a-40d1-b542-544616980d38.png)
Maybe there could be a blacklist? Data that meets the conditions will not be logged, for example: user:player action:kill include:wither_skeleton
   
   

![#dispenser](https://user-images.githubusercontent.com/46647646/188259205-1c0a738b-ac95-4345-99a6-9534102e0fcd.png)
My server uses Slimefun, which has a Woodcutter Android in it, and he chops down trees repeatedly, which also causes database bloat. Maybe use a blacklist to reduce data logging: user:#dispenser
   
   
![iron_golem](https://user-images.githubusercontent.com/46647646/188260184-161ec614-df90-4dfd-819f-405dd57e6db4.png)
Things like blacklisting also prevent junk data issues from iron golem farms and cobblestone generator with wither and something that produces a lot of duplicate data.

**Comment by vacla** [comment]
You can already blacklist, see: https://docs.coreprotect.net/config/

**Comment by XXY233** [comment]
> You can already blacklist, see: https://docs.coreprotect.net/config/
Thanks, this is awesome!
