### ISSUE TITLE
Suggestion: Add pool-settings such as maximum-lifetime

### ISSUE THREAD

**Issue by belphegorspn** [PlayPro/CoreProtect#286]
Add pool-settings so I'm able to change the maximum lifetime and stop the spam messages like 
`[22:54:33 WARN]: [net.coreprotect.hikari.pool.PoolBase] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@237e1fbb (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.`
I know this is already possible since luck perms have this on its config file or maybe just a toggle to stop the warning messages. Thank you!

**Comment by vacla** [comment]
duplicate of #199
