### ISSUE TITLE
Glowing text in signs isn't logged

### ISSUE THREAD

**Issue by Johnibur** [PlayPro/CoreProtect#29]
In 1.17, attribute `GlowingText` is not logged. This attribute is used to store whether signs text glows.

**Comment by Intelli** [comment]
New API method needs to be implemented: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/Sign.html#isGlowingText()

Will also likely require modifying the table structure in the database.

**Comment by Intelli** [comment]
Resolved in v20.0
