### ISSUE TITLE
Citizens NPC Sentinel Kills treated as players

### ISSUE THREAD

**Issue by SykoUSS** [PlayPro/CoreProtect#293]
CoreProtect throws error in console when an NPC with the Sentinel Trait kills a mob

22.10 01:06:29 [Server] WARN java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
22.10 01:06:29 [Server] WARN at CoreProtect-21.2.jar//net.coreprotect.database.logger.PlayerKillLogger.log(PlayerKillLogger.java:31)
22.10 01:06:29 [Server] WARN at CoreProtect-21.2.jar//net.coreprotect.consumer.process.PlayerKillProcess.process(PlayerKillProcess.java:15)
22.10 01:06:29 [Server] WARN at CoreProtect-21.2.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:215)
22.10 01:06:29 [Server] WARN at CoreProtect-21.2.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
22.10 01:06:29 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
22.10 01:06:53 [Server] WARN java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
22.10 01:06:53 [Server] WARN at CoreProtect-21.2.jar//net.coreprotect.database.logger.PlayerKillLogger.log(PlayerKillLogger.java:31)
22.10 01:06:53 [Server] WARN at CoreProtect-21.2.jar//net.coreprotect.consumer.process.PlayerKillProcess.process(PlayerKillProcess.java:15)
22.10 01:06:53 [Server] WARN at CoreProtect-21.2.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:215)
22.10 01:06:53 [Server] WARN at CoreProtect-21.2.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
22.10 01:06:53 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by SykoUSS** [comment]
This is the same branch of issues, but not necessarily a duplicate of

https://github.com/PlayPro/CoreProtect/issues/261

**Comment by Intelli** [comment]
Fixed in https://github.com/PlayPro/CoreProtect/commit/319d104622133e757f5c95b22c3844cf09b9d449
