### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by toxba** [PlayPro/CoreProtect#297]
Hello, my server crashed  and coreprotect seems to be the cause but i'm not sure. Here is the logs:

1719 | [18:27:15] [Thread-16/WARN]: at org.sqlite.core.DB.newSQLException(DB.java:1030)
1720 | [18:27:15] [Thread-16/WARN]: at org.sqlite.core.DB.newSQLException(DB.java:1042)
1721 | [18:27:15] [Thread-16/WARN]: at org.sqlite.core.DB.throwex(DB.java:1007)
1722 | [18:27:15] [Thread-16/WARN]: at org.sqlite.core.NativeDB._exec_utf8(Native Method)
1723 | [18:27:15] [Thread-16/WARN]: at org.sqlite.core.NativeDB._exec(NativeDB.java:97)
1724 | [18:27:15] [Thread-16/WARN]: at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:102)
1725 | [18:27:15] [Thread-16/WARN]: at CoreProtect-21.2.jar//net.coreprotect.database.Database.performCheckpoint(Database.java:94)
1726 | [18:27:15] [Thread-16/WARN]: at CoreProtect-21.2.jar//net.coreprotect.consumer.process.Process.processConsumer(Process.java:77)
1727 | [18:27:15] [Thread-16/WARN]: at CoreProtect-21.2.jar//net.coreprotect.consumer.Consumer.run(Consumer.java:133)
1728 | [18:27:15] [Thread-16/WARN]: at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by SageSphinx63920** [comment]
Could you please send the entire latest.log file? This isn't the entire error

**Comment by toxba** [comment]
[latest.log](https://github.com/PlayPro/CoreProtect/files/10050579/latest.log)

**Comment by SageSphinx63920** [comment]
your disk space could be full. Can you check it?

**Comment by toxba** [comment]
![Uploading IMG_20221120_211120.jpg…]()

**Comment by toxba** [comment]
I dont know if ou Yan see the screen but my disk space is at 7/60 go

**Comment by toxba** [comment]
Same error and my disk splace isn't full [latest2.log](https://github.com/PlayPro/CoreProtect/files/10086754/latest2.log)

**Comment by Intelli** [comment]
Filesystem error, see https://www.sqlite.org/rescode.html#ioerr_shmsize
