### ISSUE TITLE
Dont close this please - Logging players killing one another

### ISSUE THREAD

**Issue by celticpixie** [PlayPro/CoreProtect#299]
I have seen issues made here before about the ability to log players killing other players, but the responses are either not there or the issue is closed as a 'duplicate'. I see no way of possibly recording this information as action:kill pertains to entities only and :username is relating to username changes. Please add a way to log players killing other players! 

Don't just close this, please respond. #216 (as an example of previously not answered)

**Comment by Intelli** [comment]
https://github.com/PlayPro/CoreProtect/issues/216#issuecomment-1165677302
