### ISSUE TITLE
Very strange SQL Data Truncation Error with strange sentence 

### ISSUE THREAD

**Issue by jamesipod** [PlayPro/CoreProtect#30]
When I type this in chat using CMI Hexcode formatting: 

{#C32E2E>}This is a much longer test than the last ones and I just want to try the gradiants{#C32EC3<}

It comes out weird in chat, and it shows up in the console as:

[Manager] Ipod ›› This is a much longer test than the last ones and I j§xh dearst want to try the gradiants

and this error runs:

[WARNING] .... java.sql.BatchUpdateException: Data truncation: #22001
[WARNING] .... at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[WARNING] .... at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[WARNING] .... at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[WARNING] .... at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
[WARNING] .... at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
[WARNING] .... at com.mysql.cj.util.Util.handleNewInstance(Util.java:192)
[WARNING] .... at com.mysql.cj.util.Util.getInstance(Util.java:167)
[WARNING] .... at com.mysql.cj.util.Util.getInstance(Util.java:174)
[WARNING] .... at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
[WARNING] .... at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchedInserts(ClientPreparedStatement.java:755)
[WARNING] .... at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:426)
[WARNING] .... at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:794)
[WARNING] .... at net.coreprotect.consumer.process.Process.commit(Process.java:313)
[WARNING] .... at net.coreprotect.consumer.process.Process.processConsumer(Process.java:268)
[WARNING] .... at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[WARNING] .... at java.base/java.lang.Thread.run(Unknown Source)
[WARNING] .... Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: #22001
[WARNING] .... at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
[WARNING] .... at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:637)
[WARNING] .... at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:418)
[WARNING] .... at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
[WARNING] .... at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
[WARNING] .... at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
[WARNING] .... at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchedInserts(ClientPreparedStatement.java:716)
[WARNING] .... ... 6 more

Is this some strange accidental SQL injection code I accidentally found?

**Comment by Intelli** [comment]
That error means the message was too long and the full message wasn’t logged in the database.

**Comment by Intelli** [comment]
Fixed in v20.0
