### ISSUE TITLE
Item in item frame is not logged

### ISSUE THREAD

**Issue by WMGameLive** [PlayPro/CoreProtect#302]
Putting the item into the item frame or taking the item out of the item frame will not log.
Using Spigot-1.19.3 and CoreProtect-21.3.

**Comment by Intelli** [comment]
Unable to replicate.

<img width="719" alt="image" src="https://user-images.githubusercontent.com/6790859/207975573-f040a992-1962-4eb6-9c0e-c0fbb43dcf8a.png">

**Comment by WMGameLive** [comment]
Oh, sorry! I don't know this is now in the container category, thank you for the reply.
Can I suggest that let the log will also appear when you click the item frame? since clicking the item frame only display the log of placing and destroying it.
