### ISSUE TITLE
Incomplete rollback make tps low

### ISSUE THREAD

**Issue by Black-HIG** [PlayPro/CoreProtect#307]
My server crashed because thousands of entites.
When i use coreprotect and rollback somewhere, it rollback not completely and make there are a lot of entities about ten thousand, it make my server crashed quickly.
I guess it is because it doesn't rollback "kill" action but it rollback the entities' spawn events make the entities' amount is more than the server can handle.
I think you can add a checking if entities' amount after rollback will make server tps low , if it will , stop roll back entites.

**Comment by Intelli** [comment]
Duplicate of #298
