### ISSUE TITLE
Value of blockdata always the same in the result from lookup

### ISSUE THREAD

**Issue by MachiganMC** [PlayPro/CoreProtect#308]
I use the API of the plugin.
When I, first, register a log placement with `CoreProtectAPI#logPlacement`. And when I try to get a result with `CoreProtectAPI#performLookup` the value of a type of blockdata is always the same.

e.g. : The value of the `lit` blockdata is alway `false`. But when I go in the db, I see that the block placement action is registered with  the value `true`.
And it's the same with all the blockdata, always the same value for a blockdata type.

**Comment by Intelli** [comment]
Fixed in https://github.com/PlayPro/CoreProtect/commit/acb71a83a21d81b0ff2c0bdf767167d30dfd8e60

**Comment by MachiganMC** [comment]
Hey,
Could you update the Maven repository, please.
Because the repository hasn't the changement.
Thank you
