### ISSUE TITLE
Core Protect not working

### ISSUE THREAD

**Issue by SryzoTV** [PlayPro/CoreProtect#31]
I recently installed Core Protect on my SMP server to prevent grief and CP doesn't work. When I try /co or /co inspect it only says "/co <params>"

![Screenshot_1](https://user-images.githubusercontent.com/46054554/123509208-c5ef1180-d67c-11eb-8268-a88f12473231.png)

**Comment by Intelli** [comment]
CoreProtect v19 requires Spigot, Paper, Tuinity, or PurPur.

Additional information can be found in your startup log.
