### ISSUE TITLE
CoreProtect Caused "Paper Watchdog Timed Out" (Probably)

### ISSUE THREAD

**Issue by Shiroiame-Kusu** [PlayPro/CoreProtect#316]
Server: Mirai 1.19.2
CoreProtect: 21.3
Here are the logs.
[2023-01-12-2.log](https://github.com/PlayPro/CoreProtect/files/10402725/2023-01-12-2.log)
![image](https://user-images.githubusercontent.com/42903464/212097749-526d4899-2e37-46a2-8854-1f2e30bb176d.png)
I may need some help. Thanks.

**Comment by Intelli** [comment]
> IncompatibleClassChangeError

My guess would be something is incompatible with the server software you’re running. Please attempt to replicate with Paper.

**Comment by Shiroiame-Kusu** [comment]
Thanks. I'll try this later.
