### ISSUE TITLE
Inspecting a sign with hex colors displays the wrong colors in /co i

### ISSUE THREAD

**Issue by SecretlyJealous** [PlayPro/CoreProtect#317]
When you inspect a sign that has hex colors it shows the wrong colors:
![image](https://user-images.githubusercontent.com/10485646/213157059-c1759ff6-edab-4865-a89b-274b7dd17abb.png)

**How to reproduce:**
Get a plugin that allows you to use hex colors on signs such as SignEdit: https://www.spigotmc.org/resources/signedit-for-bukkit.47604/. Use signedit to set the line on a sign with hex codes, for example: `/sign set 1 &#abc123Hello` and then right click with `/co i` on the sign.

**Comment by Intelli** [comment]
Already fixed in https://github.com/PlayPro/CoreProtect/commit/12f2000085d07d5324190bda260f70405dd79f27
