### ISSUE TITLE
MySQL error spam

### ISSUE THREAD

**Issue by RhythmicSys** [PlayPro/CoreProtect#319]
There has been a consistent issue on my server that I'm getting, where CoreProtect seems to be having an issue with MySQL
The previous issues with this that I've seen on the discord, seem to be related to trying to purge large amounts of information, but these errors have not seemed to coincide with any events that I can tell.

[Latest startup log](https://pastebin.com/bWrW5pvr)
[Errors specifically](https://mclo.gs/hrwbzvH#L30) (the file was too large for pastebin)
`/co status`:
```
 ----- CoreProtect -----
Version: CoreProtect v21.3.
License: Invalid donation key. (Please check config.yml)
Database: Using MySQL. (Initial DB: 21.3)
WorldEdit: Integration enabled.
Consumer: 2 items in queue.
Discord: www.coreprotect.net/discord/
Patreon: www.patreon.com/coreprotect/
```
Server version: `git-Purpur-1888 (MC: 1.19.3)`

**Comment by Intelli** [comment]
> The total number of locks exceeds the lock table size

https://major.io/2010/02/16/mysql-the-total-number-of-locks-exceeds-the-lock-table-size-2/

**Comment by RhythmicSys** [comment]
Okay yeah I read that when I looked up the question on the discord. 
But I don't have access to the internals of the database, and to my knowledge, nothing should be removing or deleting a ton of information from there. The only connection on that database is CoreProtect, and I have around 4 concurrent players, the entire DB is 2.5GB in size. 

There should be no operations that are clogging it, and yet it's giving me this wall of errors daily. 

Is there a setting in the CP config that I've missed that limits how much info can be sent/removed to/from the database at a time? Because that's not something I have control over from the database side.

**Comment by RhythmicSys** [comment]
This is unfortunately continuing to be a major issue, and although I would like to just switch off MySQL, that's a lot of data I don't really want to lose. 

Logs from [Jan 9, 2023](https://mclo.gs/XmLvNxD#L10)
Logs from [Jan 10, 2023](https://mclo.gs/zCiWR7o#L83)
Logs from [Jan 12, 2023](https://mclo.gs/2YSE80T#L12)
Logs from [Jan 16, 2023](https://mclo.gs/rYTGKbB#L3)
Logs from [Jan 18, 2023](https://mclo.gs/dTfVo2n#L43)
Logs from [Jan 21, 2023](https://mclo.gs/Q5Q2JO1#L30)
Logs from [Jan 24, 2023](https://mclo.gs/ZU3AyZy#L8)
Logs from [Jan 26, 2023](https://mclo.gs/Q5Q2JO1#L30)

There are no options for someone who uses a hosting site to modify how much the database can take in at once, and unless I'm mistaken, there's no options in the config either. 

These are the database options on bloom host, that I have

![Screenshot from 2023-01-27 12-32-24](https://user-images.githubusercontent.com/45906780/215193557-d89c26f5-71c0-4771-984a-42ebac76f2c5.png)
![Screenshot from 2023-01-27 12-34-34](https://user-images.githubusercontent.com/45906780/215193571-b9d26d6f-9492-4b87-b235-5f9452e1f667.png)

The only modifiable option is the `Allowed Connections` tab. There is nowhere for me to edit anything more advanced than that. 

If this issue is already being addressed I apologize for pushing it, but it currently seems to be dismissed, and this seems like something that could be addressed within the plugin

**Comment by Intelli** [comment]
I advise you contact your host for support regarding their services.

You're correct that this is abnormal, but the issue here isn't on CoreProtects end.

**Comment by RhythmicSys** [comment]
Alright, thank you for your time
