### ISSUE TITLE
Initializing Legacy Material Support?

### ISSUE THREAD

**Issue by molor** [PlayPro/CoreProtect#32]
Build this (black concrete, red concrete, lever):
![image](https://user-images.githubusercontent.com/19989717/123794643-bcb7ac00-d8eb-11eb-841f-237d8c7cad56.png)

Now destroy the black concrete block above the lever.
See `Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!` in server console and lag for 3-5 seconds :/

```
CoreProtect v19.5
git-Paper-777 (MC: 1.16.5)
Java 16

Plugins (7): CoreProtect, dynmap, Essentials, EssentialsGeoIP, EssentialsSpawn, LuckPerms, NoCheatPlus
```

**Comment by Intelli** [comment]
Fixed in v20.0
