### ISSUE TITLE
Make PreLogEvent cancellable

### ISSUE THREAD

**Issue by DerSimeon** [PlayPro/CoreProtect#325]
Hey,

currently, it is not possible to run custom checks in order to prevent a certain log from happening.

On our Server, we need to sometimes disable logging for specific players, which as of right now is not possible.
Whether this is due to the fact that the implementation is incomplete or the huge performance impact a constant check of for example Permission would be. 

We need to be able to check if a player is in a specific ArrayList, and if so cancel the event to prevent the Log from being saved.
Since the API currently has no support for this, we would like to either get a suggestion for an alternative implementation or suggestions on properly implementing the cancellable PreLogEvent.

**Comment by Kryniowesegryderiusz** [comment]
Same for me. I have some custom features on my server like stone generators, which are clogging my CO databases. I'd like to implement additional checks for my own, as its not possible to disable block logging in blacklist.txt rn.

**Comment by xCraimax** [comment]
That's actually the same thing for me. That would be very useful!

**Comment by erxson** [comment]
<img src="https://tenor.com/view/discord-ping-pingus-bingus-cat-gif-18905873">

**Comment by Matz3000-Matti** [comment]
Absolute the same thing for me. I need it too! Add this please!🙏

**Comment by milosz1406** [comment]
Same for me. I also need it.

**Comment by wzakrzewski** [comment]
Also need it, please add it if you can <3

**Comment by JaHollTV** [comment]
Any update? This would be really useful.

**Comment by Intelli** [comment]
Implemented in https://github.com/PlayPro/CoreProtect/commit/1a06e6a6bf8cd469b6f127803363593ffd6f690f
