### ISSUE TITLE
Suggestion: Adding arguments to /co inspect

### ISSUE THREAD

**Issue by tori1277** [PlayPro/CoreProtect#326]
Currently, /co inspect locks the user to only being able to look at all actions that happen in one block or container, so when that block or container has multiple pages of logs, it gets tedious to read and harder to look for specific logs. The 2nd best option is to use /co lookup, but the issue is that /co lookup isnt specific about y-level or which chests/containers were interacted with. My suggestion is that /co inspect could also have room for arguments like /co lookup. For example, /co inspect include:elytra time:1h would only show what interactions include an elytra in the past hour in the chest that was right-clicked, so in this way, users can identify interactions in one specific chest without having to scroll through 30+ logs to find one specific action in the chest.

**Comment by Intelli** [comment]
CoreProtect already has a solution for this implemented.

You can inspect a chest, and then use #container as the user to target that chest in a lookup.
