### ISSUE TITLE
[BUG]Unable to log “HT's TreeChop”MOD -block.

### ISSUE THREAD

**Issue by KiWinger** [PlayPro/CoreProtect#329]
HT's TreeChop: https://beta.curseforge.com/minecraft/mc-mods/treechop

![image](https://user-images.githubusercontent.com/49084827/220160107-0c66950a-25ce-4033-8eff-afe068d42bd0.png)
This is an Minecraft Acacia tree.

![image](https://user-images.githubusercontent.com/49084827/220161311-06e019f2-1b8f-487f-b603-e44978cef6d5.png)
![image](https://user-images.githubusercontent.com/49084827/220162186-f42676bd-3eb2-4477-a494-29953911b96d.png)
"HT's TreeChop“Mod cause trees to be cut down quickly.

![image](https://user-images.githubusercontent.com/49084827/220162331-09156478-52a0-4ec7-97ad-392a9855c1e2.png)
Lookup result is only one block.

![image](https://user-images.githubusercontent.com/49084827/220162595-75351870-4c17-4843-a3c4-1049c1f7586e.png)
Rollback is the same, only one block.

**Comment by Intelli** [comment]
Not a bug, that plugin either needs to add support for CoreProtect, or you can use a plugin that already supports CoreProtect such as SmoothTimber: https://www.spigotmc.org/resources/smoothtimber.39965/
