### ISSUE TITLE
[BUG] /co i does not save the actions of minecarts with chests, and boats with chests

### ISSUE THREAD

**Issue by qqsob** [PlayPro/CoreProtect#330]
![image](https://user-images.githubusercontent.com/103686875/222980379-9d316178-31b6-402e-a07e-a5a63a534388.png)
![image](https://user-images.githubusercontent.com/103686875/222980390-e744a3f4-3869-4fba-b841-3c0b02c9f3fb.png)

Our server is periodically grifered, and resources are taken away from the twink accounts. And we can't track these actions in any way. This needs to be resolved

**Comment by Intelli** [comment]
Duplicate of #127 / #233

Note that hopper transactions *are* logged, so for example, data is logged for transferring items from a chest to a minecart chest.
