### ISSUE TITLE
[Suggestion] Item Names

### ISSUE THREAD

**Issue by SleepiiRaven** [PlayPro/CoreProtect#332]
Hello developers! Let's say that someone in a server was running a potion shop, or selling tiered items in a MMO server. It's really hard to differentiate different types of potions or differently named armor with this log system. Therefore, my proposition is: Item Names! With the current GUI, it looks something like this:
#/(m/d/w/y) ago +/- [PlayerName] added x1 [item type]
  My current potion chest's logs looks something like this: 
![image](https://user-images.githubusercontent.com/104394825/223847616-6e8a48e4-5ffe-45ce-ae6e-181724ee4e96.png)
  I don't know which potions are which in my logs. However, I propose something like this:
#/(m/d/w/y) ago +/- [PlayerName] added x1 [Item Name] ([Item Type]).
  This can be formatted differently, but along with this suggestion, I'll be making a pull request, just to make it all the easier for you all! Thanks so much for considering this suggestion,
  
  - SleepingRaven

**Comment by Intelli** [comment]
Already implemented: https://github.com/PlayPro/CoreProtect/commit/5d6fd60d40281f51fbd248dc7099e008de67b862

Will be in the next release of CoreProtect

(#67)

**Comment by SleepiiRaven** [comment]
> Already implemented: [5d6fd60](https://github.com/PlayPro/CoreProtect/commit/5d6fd60d40281f51fbd248dc7099e008de67b862)
> 
> Will be in the next release of CoreProtect
> 
> (#67)

Oh that's great! Will it be implemented in the next 1.18.2 version? Or is that version no longer being updated?

**Comment by Intelli** [comment]
The next release will continue to support 1.18.2, with 1.15 - 1.20 being supported.
