### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by SrMonsterYT** [PlayPro/CoreProtect#334]
There are many plugins that have this configuration:

1° https://prnt.sc/pMZ1JqHdDfaZ
2° https://prnt.sc/dP-w3cPS_VV9

in your configuration, can you define 1 X day to delete files so you don't have to program it to execute the /co purge command, this would help a lot, I don't understand how this amazing plugin doesn't have this option yet

**Comment by Intelli** [comment]
Duplicate of #176

**Comment by SrMonsterYT** [comment]
sorry I didn't see that I already had a suggestion I will delete it and comment there
