### ISSUE TITLE
hopper_minecart and chest_minecart do not log items placed in them

### ISSUE THREAD

**Issue by KO9I** [PlayPro/CoreProtect#340]
Hello, I noticed such a problem that "hopper_minecart" does not register the items placed in it, which is why it is impossible to track resources, at the moment, in order to track the missing resources, you need to know the player's nickname and track the rails through it and hope that he did not move "hopper_minecart" to another place with a fishing rod.
At the moment, core protect does not register who put and who took the goods from hopper_minecart, will this be implemented in the future? After all, if there are several violators, it is almost impossible to find stolen resources.

**Comment by Intelli** [comment]
Duplicate of #127.
