### ISSUE TITLE
Coreprotect & sign data

### ISSUE THREAD

**Issue by unimatrixgit** [PlayPro/CoreProtect#342]
So i just discoverd in the latest snapshot you can edit signs by clicking them ,  i hope coreprotect will log these interactions and the data and roll it back ? right? please

**Comment by MrBlueRay** [comment]
That is a good point could be a problem if it does not. But there is also the issue of signs now being dual sided thats a new system they are going to need to look at now.

**Comment by Intelli** [comment]
Please refrain from submitting tickets regarding snapshots, as:

1. CoreProtect does not support snapshots.
2. Functionality in snapshots may differ from functionality in releases.

CoreProtect already supports sign editing. Dual sided signs are not presently supported.
