### ISSUE TITLE
[ERROR] Events not getting parsed on Magma Server

### ISSUE THREAD

**Issue by Relaxing9** [PlayPro/CoreProtect#346]
I keep getting this spammed on my Minecraft Server:
[https://paste.gg/p/anonymous/97a79df9aedb4e1184798b61bdf5b5ac](https://paste.gg/p/anonymous/97a79df9aedb4e1184798b61bdf5b5ac)

Minecraft Server Version: Magma version 1.18.2-129359fa (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge Version 40.2.1)
Core Protect Version: 21.3

**Comment by vacla** [comment]
Duplicate of #336

**Comment by Relaxing9** [comment]
OK...

**Comment by Relaxing9** [comment]
But where can I download it?

**Comment by Intelli** [comment]
A precompiled development build is available at https://www.patreon.com/coreprotect

**Comment by Relaxing9** [comment]
<https://mclo.gs/dciJyeQ>
No longer get InventoryClickEvent errors with Magma
But I still get: HangingPlaceEvent, HangingBreakByEntityEvent

Note: Using latest commit on Core Protect master branch.
Minecraft Server Version: Magma version 1.18.2-1a50ede7 (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge Version 40.2.1)
