### ISSUE TITLE
[Feature Request] Additional flag added to purge, so it bypasses creating a temp file

### ISSUE THREAD

**Issue by malonnnn** [PlayPro/CoreProtect#353]
My current DB is almost 70GB in size, and I need to free space.

The issue is: I don't know how big the temp file will be. I need to free space, not add to it by making a giant file, which may max out available space, causing even more issues.

Can we please add a flag like `/co purge t:30d -notempfile` to simply delete the data straight from the DB instead of copying data?

**Comment by Intelli** [comment]
Not possible to reduce an SQLite database file size without it creating a copy.

https://www.sqlite.org/lang_vacuum.html (See section 3)

**Comment by malonnnn** [comment]
thank you
