### ISSUE TITLE
CoreProtect Does Not Log Items In a Campfire

### ISSUE THREAD

**Issue by bipedd** [PlayPro/CoreProtect#357]
So I am running CoreProtect Version 21.3, and when you place an item in a campfire it does not get logged by CoreProtect:
![image](https://user-images.githubusercontent.com/77213949/233204349-76a2d721-efe7-4f19-bb4c-708653440081.png)
![image](https://user-images.githubusercontent.com/77213949/233204543-cc58ad4a-cab4-4270-9fce-7d5827cb329a.png)
![image](https://user-images.githubusercontent.com/77213949/233204486-abf9789a-2cec-4de7-937a-d231a5288875.png)

**Comment by Intelli** [comment]
Inventory transaction logging added for campfires in https://github.com/PlayPro/CoreProtect/commit/e7a6f21d88d7ff40e9d94811dec6f2f1f48d739d
