### ISSUE TITLE
Failed to validate connection 

### ISSUE THREAD

**Issue by cammposrafaela** [PlayPro/CoreProtect#362]
[Tue 13:15:12 WARN  net.coreprotect.hikari.pool.PoolBase] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@42a7f795 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.

I get this warning at console, how may i fix it?

**Comment by Intelli** [comment]
Please provide your server log.
