### ISSUE TITLE
Consider fitting the following Folia?

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [PlayPro/CoreProtect#363]
I hope your plugin will work with Folia, I love your plugin, but I'm sorry it doesn't work with Folia :(

**Comment by vacla** [comment]
@xiaoyueyoqwq the next update will have support for folia

**Comment by Intelli** [comment]
Fola is already supported: https://github.com/PlayPro/CoreProtect/commit/7170e2945269f6aa7f6a8468cad8e2ae473357eb

This can be tested in the v22.0 Development Build 1: https://www.patreon.com/posts/coreprotect-edge-80854439

**Comment by xiaoyueyoqwq** [comment]
> Fola is already supported: https://github.com/PlayPro/CoreProtect/commit/7170e2945269f6aa7f6a8468cad8e2ae473357eb
> 
> This can be tested in the v22.0 Development Build 1: https://www.patreon.com/posts/coreprotect-edge-80854439

okay, thanks so much

**Comment by darkKing5319** [comment]
> Fola уже поддерживается: [7170e29](https://github.com/PlayPro/CoreProtect/commit/7170e2945269f6aa7f6a8468cad8e2ae473357eb)
> 
> Это можно протестировать в сборке 1 версии 22.0 для разработчиков:https://www.patreon.com/posts/coreprotect-edge-80854439
Sorry to distract you, but you can throw the file here, patreon doesn't work for me. :’-)

**Comment by LWJerri** [comment]
> > Fola уже поддерживается: [7170e29](https://github.com/PlayPro/CoreProtect/commit/7170e2945269f6aa7f6a8468cad8e2ae473357eb)
> > This can be tested in the v22.0 Development Build 1:https://www.patreon.com/posts/coreprotect-edge-80854439
> 
> Sorry to distract you, but you can throw the file here, patreon doesn't work for me. :’-)

Just use VPN =)
