### ISSUE TITLE
Add itemsadder support

### ISSUE THREAD

**Issue by tyepavitt** [PlayPro/CoreProtect#365]
Add ItemsAdder support to be able to inspect custom ItemsAdder blocks/furniture and be able to co rollback them correctly.

Here's the plugin page: https://www.spigotmc.org/resources/%E2%9C%A8itemsadder%E2%AD%90emotes-mobs-items-armors-hud-gui-emojis-blocks-wings-hats-liquids.73355/

**Comment by Intelli** [comment]
They would have to add support for CoreProtect in their plugin, not the other way around.

**Comment by evilsaloon** [comment]
> They would have to add support for CoreProtect in their plugin, not the other way around.

The creator of ItemsAdder says that it's impossible to do so because CoreProtect doesn't support non-vanilla block dara. See: https://github.com/PluginBugs/Issues-ItemsAdder/issues/165#issuecomment-1576536707
