### ISSUE TITLE
Possible glitch after changing and reloading configuration "player-interactions"

### ISSUE THREAD

**Issue by mfritz2006** [PlayPro/CoreProtect#366]
**Environment:** 
- Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
- CoreProtect-21.3
- paper-1.17.1-411

**Description:**
After changing `player-interactions` from `false` to `true` and performing `co reload`, interactions with doors and buttons can neither be logged nor looked up. However other player interactions such as with fence gates, trapdoors or clicking containers are fine.

**Steps to reproduce:**
- Before starting the server, set `player-interactions` to false in config.yml;
- Start the server;
- Player interactions can be inspected, but not logged, which is normal behaviour;
- Change `player-interactions` from `false` to `true` and perform `co reload`;
- Enable the inspector and right click a door, or click a button;
- The door does not open or close, the button does not activate. Inspector returns "No transactions found at this location". Past interactions do not show up, and new interactions are not logged;
- Right click a fence gate, a trapdoor or a container and watch the plugin function correctly.

I've seen this problem on another paper 1.18.2 server and managed to reproduce locally. The only workaround I've discovered is to restart the server.

There seems to be no relevant log entries among the server log. Not sure if there's a logging verbosity config that needs to be increased.

config.yml: http://paste.debian.net/plainh/993fdd26

I'm not totally sure if this is an actual issue with CoreProtect or just a misconfiguration, but thanks in advance!

**Comment by Intelli** [comment]
To clarify, does it log correctly if you start the server with `player-interactions` set to true?

**Comment by Intelli** [comment]
Aight I replicated the issue, that's pretty weird. Looking into it now.
