### ISSUE TITLE
Create mod support

### ISSUE THREAD

**Issue by Gfortes985** [PlayPro/CoreProtect#370]
can I add new log object from mod using api? if yes, then how..

**Comment by vacla** [comment]
@Gfortes985 which "mod" would you mean?

**Comment by Gfortes985** [comment]
@vacla create

**Comment by Gfortes985** [comment]
@vacla create

**Comment by vacla** [comment]
@Gfortes985 coreprotect doesnt support officially hybrid server software.

**Comment by windy664** [comment]
is there a same mod for hybrid server software...？
