### ISSUE TITLE
`Performing 13,616,431 upgrade. Please wait...` stuck or very slow

### ISSUE THREAD

**Issue by twseer67875** [PlayPro/CoreProtect#375]
Sometimes my server shuts down with `Performing {amount} upgrade. Please wait...` and is very slow
I basically ruled out SSD or other hardware read and write problems, and other very large tables databases do not have this problem, only CoreProtect will happen
What should I do?

Minecraft Version: `This server is running Paper version git-Paper-404 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: f9dc371)`
Plugin Version: `CoreProtect version 21.3`
MySQL Version: `5.7.39`

**Comment by twseer67875** [comment]
Is anyone home?😃

**Comment by tackleza** [comment]
I'm just a someone passed by. Check CPU Used Ram Used.
Check is your mysql doing something? processing something check what user is doing what with phpmyadmin?

There is nothing to do with CoreProtect. Blame your MySQL Server or your hardware. Or your MySQL Tune settings. You need to handle and tune your my.cnf by yourself to handle to make things faster.

Unless you provided the info what SQL query that process so slow. Then the creator might fix the problem if the problem is from CoreProtect (Bug)

**Comment by twseer67875** [comment]
> I'm just a someone passed by. Check CPU Used Ram Used. Check is your mysql doing something? processing something check what user is doing what with phpmyadmin?
> 
> There is nothing to do with CoreProtect. Blame your MySQL Server or your hardware. Or your MySQL Tune settings. You need to handle and tune your my.cnf by yourself to handle to make things faster.
> 
> Unless you provided the info what SQL query that process so slow. Then the creator might fix the problem if the problem is from CoreProtect (Bug)

My CPU usage is very low, almost always below 30%. Apart from the fact that my memory is occupied by adjusting innodb_buffer_pool_size to 8GB out of my total 16GB of memory, there doesn't seem to be any other apparent resource depletion issues. In my database, apart from CoreProtect, there are many other tables using the same database. Only CoreProtect experiences this slow read and write problem. I'm not sure what the reason is, so I'm asking here. However, it seems that this issue is not being addressed by the plugin author.

**Comment by twseer67875** [comment]
> > I'm just a someone passed by. Check CPU Used Ram Used. Check is your mysql doing something? processing something check what user is doing what with phpmyadmin?
> > There is nothing to do with CoreProtect. Blame your MySQL Server or your hardware. Or your MySQL Tune settings. You need to handle and tune your my.cnf by yourself to handle to make things faster.
> > Unless you provided the info what SQL query that process so slow. Then the creator might fix the problem if the problem is from CoreProtect (Bug)
> 
> My CPU usage is very low, almost always below 30%. Apart from the fact that my memory is occupied by adjusting `innodb_buffer_pool_size` to 8GB out of my total 16GB of memory, there doesn't seem to be any other apparent resource depletion issues. In my database, apart from CoreProtect, there are many other tables using the same database. Only CoreProtect experiences this slow read and write problem. I'm not sure what the reason is, so I'm asking here. However, it seems that this issue is not being addressed by the plugin author.

**Comment by tackleza** [comment]
So that is your MySQL doing (Upgrading Table? SQL ALTER TABLE?)
And the problem is server is starting... Performing upgrade... and it take so long and your Minecraft server shutdown by (Watchdog?) then Upgrading Table Failed?

If yes, then you should disable watchdog until Upgrade table is finished

**Comment by Intelli** [comment]
Please provide your server log.

I'd suspect the issue is that something is generating significant amounts of invalid log data, you should ideally try to determine what's being logged.
