### ISSUE TITLE
Core protect can't write to MySQL on 1.19.4

### ISSUE THREAD

**Issue by JHarris12345** [PlayPro/CoreProtect#377]
On 1.19.4 (This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)

There are no startup errors at all. When you shut down the server, the plugin gets stuck doing "X items left to log. Please wait..."

Here is a screenshot. This freezes the server
https://gyazo.com/4c14910dd84582f7a6f1bc4531f073af

**Comment by tackleza** [comment]
You did't provided any info.

What data storage did you use? flatfile? mysql? what mysql version if mysql?.
What mysql server did you use? localhost? or remote host?

**Comment by Intelli** [comment]
MySQL 5.6 issue, updating MySQL should resolve the issue.

**Comment by JHarris12345** [comment]
> MySQL 5.6 issue, updating MySQL should resolve the issue.

I am on MariaDB 10.8

**Comment by Intelli** [comment]
Please provide your server log, including startup and the usage of `co status`

**Comment by JHarris12345** [comment]
I solved this by updating MariaDB
