### ISSUE TITLE
No logging for placing of liquid (source) block

### ISSUE THREAD

**Issue by RedstoneFuture** [PlayPro/CoreProtect#383]
The following config was used to try to track the placement of lava. The **black** marked places were marked with "#lava placed lava". But the **white** marked places **has no entry**.

![grafik](https://github.com/PlayPro/CoreProtect/assets/4140635/d6c5251d-8f11-47dc-bc38-06f2a10562d1)

```
# Logs water flow. If water destroys other blocks, such as torches,
# this allows it to be properly rolled back.
water-flow: true

# Logs lava flow. If lava destroys other blocks, such as torches,
# this allows it to be properly rolled back.
lava-flow: true

# Allows liquid to be properly tracked and linked to players.
# For example, if a player places water which flows and destroys torches,
# it can all be properly restored by rolling back that single player.
liquid-tracking: true
```

![grafik](https://github.com/PlayPro/CoreProtect/assets/4140635/5fd172bc-b6a8-486c-9204-35de6eaf1352)

Same with using of dispenser.

_tested with CP version v21.3 on PaperMC 1.19.4_

**Comment by Intelli** [comment]
Sounds like some other plugin is interfering with the logging of lava placement.

If the source block is logged, then the rest of the liquid spread will be logged under the player name.

**Comment by RedstoneFuture** [comment]
Ok, I will retest it in a clean setup.

**Comment by RedstoneFuture** [comment]
Oh. I mistakenly did not set the "buckets" setting to "true". Sorry. ^^
