### ISSUE TITLE
[1.20] Sign back text doesn't get rolled back

### ISSUE THREAD

**Issue by Podgorica** [PlayPro/CoreProtect#384]
Both the front and back messages do seem to be logged by CoreProtect

![image_2023-06-14_20-32-48](https://github.com/PlayPro/CoreProtect/assets/70448311/0cb79c1c-452e-4adb-9ddf-678706ce2c28)

After the sign is destroyed and then restored, the front of the sign says "FRONT" as expected, but the back of the sign is blank.

**Comment by ehx-v1** [comment]
I guess that's one of the reasons current versions are labelled as "up to 1.19", even though most features work on 1.20 just fine.

**Comment by Intelli** [comment]
Added in https://github.com/PlayPro/CoreProtect/commit/4e43a42662fe84351ae718478f23870cb6b84425
