### ISSUE TITLE
CoreProtect For Fabric??

### ISSUE THREAD

**Issue by Blobanium** [PlayPro/CoreProtect#395]
i run a server with one on spigot and one on fabric, all of the mods on the fabric server are server side so everyone can join. And i was willing to ask if you have plans on porting the project to fabric?

**Comment by vacla** [comment]
There is ledger that kinda basically does the same thing

**Comment by vacla** [comment]
@Orlaando-dev the ledger dev is working on the performance improvements of the database right now

**Comment by Intelli** [comment]
Duplicate of #37
