### ISSUE TITLE
minutes flag is broken

### ISSUE THREAD

**Issue by JHarris12345** [PlayPro/CoreProtect#396]
You cannot use the "minutes" timeframe in rollbacks:

https://gyazo.com/da970ca1dbe150c2bd64a1087e5e4332

**Comment by Intelli** [comment]
Unable to replicate

<img width="771" alt="image" src="https://github.com/PlayPro/CoreProtect/assets/6790859/1cfa0ce8-11d3-4e06-ab66-1094bbaf9459">
