### ISSUE TITLE
Is it possible to have CoreProtect record the owner of #tnt #fire etc.

### ISSUE THREAD

**Issue by Zhou-Shilin** [PlayPro/CoreProtect#398]
_Sorry, I'm using a translator, which causes my statements may not make sense sometimes._
When a player uses TNT or fire to destroy something, CoreProtect will only record `#tnt` or `#fire`, is it possible to record both the player who lit the tnt/fire?

**Comment by malpkakefirek** [comment]
You can lookup for user placing tnt or fire

**Comment by Zhou-Shilin** [comment]
> You can lookup for user placing tnt or fire

How? Block by block?

**Comment by malpkakefirek** [comment]
e.g. `/co lookup action:+block include:tnt time:1d radius:50` (you may need to change time and radius)
You can also do `radius:#global` or `radius:#world` if you don't have a lot of players that would place tnt. For the fire you should also add `exclude:#fire` so you don't get spammed with `#fire placed fire` (e.g. `/co lookup action:+block include:fire time:1d radius:50 exclude:#fire`

**Comment by Zhou-Shilin** [comment]
Thanks!
