### ISSUE TITLE
Hope CoreProtect can record the Fawe plugin

### ISSUE THREAD

**Issue by 1364520770** [PlayPro/CoreProtect#404]
I think this is a very good plugin that supports the Worldedit plugin, but it does not support recording the actions done by the Fawe plugin. Fawe is a remake of Worldedit, which allows for better server performance, and many servers are starting to use the Fawe plugin. Hopefully, authors can support Minecraft 1.20 as soon as possible and support the Fawe plugin. Thank you!
Reference link for Fawe plugin: https://www.spigotmc.org/resources/fastasyncworldedit.13932/

**Comment by vacla** [comment]
Afaik you need blockshub installed for it.

**Comment by Intelli** [comment]
FAWE is already semi-supported. You have to enable it within FAWE.

**Comment by fengzero123** [comment]
where it is，i cant find
