### ISSUE TITLE
[Request] Translate fix and reprint authorization

### ISSUE THREAD

**Issue by DreamVoid** [PlayPro/CoreProtect#41]
Hi,
First of all, thanks for open source!
I noticed that Simplified Chinese translate has some problems, so I [made a PR](https://github.com/PlayPro/CoreProtect/pull/40) to fix. Hope that the author agreed to merge.
In addition, can I reprint CoreProtect to MCBBS(A Minecraft forum in China, which can also release original or reprinted plugin)? I believe that server owners from China will like your plugin. Also, I will mark you as the author, link to your SpigotMC and Github and never profit from them. I hope you can agree to my request.
Best regard <3

**Comment by Intelli** [comment]
Thanks, merged! And you may post the plugin on MCBBS.
