### ISSUE TITLE
Implentment of config for HikariCP

### ISSUE THREAD

**Issue by ItzMiracleOwO** [PlayPro/CoreProtect#416]
Hi. I just want to ask if there is any plan of implenting HikariCP options in the future?
For example, configuring Java Config `setConnectionTimeout()` and `setMaximumPoolSize()` to avoid `HikariPool-1 - Connection is not available, request timed out after 30000ms for very tiny load server`

**Comment by Intelli** [comment]
Maximum pool size was already made configurable: https://github.com/PlayPro/CoreProtect/commit/6045799fea4645f493d60b680f2c91cd71e351de
