### ISSUE TITLE
[Request] MySQL SSL support.

### ISSUE THREAD

**Issue by SvenjaReissaus** [PlayPro/CoreProtect#427]
I would like to be able to connect to MySQL using SSL, currently there's no option to enable SSL in the `config.yml`, so the connection is being blocked.

**Comment by Intelli** [comment]
Implemented in https://github.com/PlayPro/CoreProtect/commit/0edf160f4351bb348133c292d1e5f371ff3caba9

**Comment by SvenjaReissaus** [comment]
Thank you very much!
