### ISSUE TITLE
Add an event to the creature's fall to death

### ISSUE THREAD

**Issue by BangXi** [PlayPro/CoreProtect#432]
example：Now it's #villager kill villager

**Comment by welove69** [comment]
#Sheep kill Sheep😂

**Comment by welove69** [comment]
Idon' Tervante Torrecode, Tedis, Ben Somkritu Rez, Fromfarin
These records are not necessary for some biological farms that rely on falling to their deaths

**Comment by Intelli** [comment]
Implemented in https://github.com/PlayPro/CoreProtect/commit/f7fea2b298a0ee60c9d2fafe3b86e3831faf7acb
