### ISSUE TITLE
Wither block damage isn't logged

### ISSUE THREAD

**Issue by tori1277** [PlayPro/CoreProtect#438]
When running trying to look up the blocks the wither broke for a rollback, the wither's block-breaking actions aren't logged. I've tried using #wither, #wither_skull, and #explosion, but none have been able to help us find logs from the griefing. Kills and deaths from the wither seem to log just fine, but not blocks. Using past versions of Coreprotect, we've been able to log and rollback Wither damage just fine, but it seems like Coreprotect v22.0 isn't logging wither block damage.

**Comment by Intelli** [comment]
Unable to replicate

<img width="463" alt="image" src="https://github.com/PlayPro/CoreProtect/assets/6790859/147a3317-3f55-4442-b1a0-accd0fd7405f">

**Comment by DereC4** [comment]
Happening to me too, is there any config option that might disable this? perhaps we accidentally turned it on

For reference creeper explosions are still logged perfectly fine on our world
