### ISSUE TITLE
[help]If set to cancel the recording of deaths of individual organisms

### ISSUE THREAD

**Issue by welove69** [PlayPro/CoreProtect#442]
If set to cancel the recording of deaths of individual organisms
The Zombified Piglin biological farm inside the server records hundreds of thousands of pages, and I want to unrecord the record of the player killing Zombified Piglin separately,Still want to keep records of the deaths of other creatures
blacklist.txt：
#Zombified_Piglin
Doesn't seem to work

**Comment by Intelli** [comment]
For entity kills, the blacklist blocks based on the name of the user/entity doing the killing.

The name of the entity being killed isn't directly processed or logged.
