### ISSUE TITLE
Item destruction is not logged

### ISSUE THREAD

**Issue by ByteExceptionM** [PlayPro/CoreProtect#443]
I have all settings in the config on `true`. I have debugged the class https://github.com/PlayPro/CoreProtect/blob/master/src/main/java/net/coreprotect/listener/player/PlayerItemBreakListener.java as well. The code goes up to here: https://github.com/PlayPro/CoreProtect/blob/master/src/main/java/net/coreprotect/listener/player/PlayerItemBreakListener.java#L33. What happens after that, no idea. In any case, it is not logged when, for example, I break a shovel.

![image](https://github.com/PlayPro/CoreProtect/assets/47250043/9f10b04b-dac1-447e-a2df-fcfb17bfa0a3)

![image](https://github.com/PlayPro/CoreProtect/assets/47250043/4faca425-a8cb-45e0-a712-b442caeba695)

I checked it with `/co l include:wooden_shovel time:10m`.
Result:
![image](https://github.com/PlayPro/CoreProtect/assets/47250043/0a48e6a8-7d19-4760-871f-ab8aa9bd368b)

The queue is also empty:
![image](https://github.com/PlayPro/CoreProtect/assets/47250043/2d68a757-b58f-407f-ae50-0af0e0f2f690)

**Comment by Intelli** [comment]
Item destruction is just logged under the players inventory data.

`/co lookup username a:inventory t:1m`

<img width="505" alt="image" src="https://github.com/PlayPro/CoreProtect/assets/6790859/fc2d9105-f4e5-431f-924f-e97e20fadb41">

To rollback a players inventory, you also need to include `a:inventory`
