### ISSUE TITLE
Disable logging of useless blocks

### ISSUE THREAD

**Issue by WarnDa** [PlayPro/CoreProtect#444]
Hello,
I'm using coreprotect only to log stealing abuse, item stealing, and protection against block place/break on quests.
But coreprotect is loggin every block that player place/break, so if he is mining during 1hr, it will adds a lot of useless block loggin, and also as it's doing big mysql requests each time, it creates iowait..

In the blacklist.txt, we can only logs "non player actions", and I already tried to set some blocks inside but it still logs when I place or break them.
![image](https://github.com/PlayPro/CoreProtect/assets/31826333/85569006-2c1e-4051-9de3-470c0c389d4f)

**Comment by WarnDa** [comment]
Here are the quantity of requests it does to the database, and it creates iowait up to 3% (I'm getting 13900K and samsung 990 PRO NVME ssd)
![image](https://github.com/PlayPro/CoreProtect/assets/31826333/bf79e66a-2237-4fa6-9c40-9348bee47553)

**Comment by Intelli** [comment]
Implemented in https://github.com/PlayPro/CoreProtect/commit/7c61a335714e25a7d7d17f143302c0ec9d2543c7
