### ISSUE TITLE
[BUG] Hopper item transfers will not be recorded

### ISSUE THREAD

**Issue by kevinwang-0916** [PlayPro/CoreProtect#446]
CoreProtect 22.1
Items passing through hoppers are not recorded:(

**Comment by mov51** [comment]
Do you have the `hopper.disable-move-event` option disabled in the Paper config?

**Comment by kevinwang-0916** [comment]
Nope 
disable-move-event: false

**Comment by Intelli** [comment]
Unable to replicate, logging is working normally when testing.
