### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "pe" is null

### ISSUE THREAD

**Issue by djoveryde** [PlayPro/CoreProtect#448]
While attempting to run core protect on my minecraft 1.19.2 server I am getting the following error. Unsure how to fix it

https://pastebin.com/1NunY2hT

**Comment by Intelli** [comment]
CoreProtect only officially supports Craftbukkit, Spigot, Paper, Purpur, Folia, and Geyser.
