### ISSUE TITLE
Rollback won't work properly on Folia

### ISSUE THREAD

**Issue by AltronMaxX** [PlayPro/CoreProtect#453]
The problems occur when rollbacks occur in different worlds with radius #global. It's works for several chunks and then stucks and don't ends. Also, if there're players in chunks where rollbacks is happening, plugins starts spamming errors into console.
Error stacktrace: https://pastebin.com/vK1uQLJg

**Comment by Intelli** [comment]
Fixed the error here: https://github.com/PlayPro/CoreProtect/commit/9f3196dc973e751d64df88292d1548e6436fc83b

If you have any other issues or errors, please post a separate issue.
