### ISSUE TITLE
Rollback stucks on Folia

### ISSUE THREAD

**Issue by AltronMaxX** [PlayPro/CoreProtect#454]
When you trying to use rollback with radius:#global it stucks on ofe of the chunks and will end rollback on this chunk after five minutes. At the same time all logs says, that everything happened well even in chunks that were not affected by rollback. And in the end, this issue doesn't give any errors into server logs.

Maybe the reason of this problem connected with some worlds errors, because if you perform rollback only for specific world it will work properly.

**Comment by AltronMaxX** [comment]
Perhaps this problem is somehow related to this #453

**Comment by Intelli** [comment]
Unable to replicate.

Steps tested:
1. Made changes in all worlds at various locations.
2. Teleported to the far reaches of a world
3. Restarted server (also tested without restarting)
4. Ran global rollback for past day

The rollback runs as expected.

**Comment by andreypfau** [comment]
same issue

**Comment by Intelli** [comment]
> same issue

Please ensure you’re running CoreProtect v22.2 with the latest build of Folia.
