### ISSUE TITLE
[Feature] Show Coordinate of affected block/container in lookup

### ISSUE THREAD

**Issue by gxjakkap** [PlayPro/CoreProtect#465]
When using /co lookup, It could show the affected block/container's coordinate. Like in this example,

![image](https://github.com/PlayPro/CoreProtect/assets/55027998/3e2a0000-e0ac-4d26-9144-e76117acf45a)

It would be beneficial to show which chest the diamonds were taken from. That would provide more help to the admins.

**Comment by Intelli** [comment]
Already displayed for container or item lookups

<img width="457" alt="image" src="https://github.com/PlayPro/CoreProtect/assets/6790859/746afba6-14f3-428f-a0c1-751146f7241d">

You're likely performing an inventory lookup, which _isn't_ doing a lookup on container locations.
