### ISSUE TITLE
Overstacked items issue

### ISSUE THREAD

**Issue by JHarris12345** [PlayPro/CoreProtect#471]
I have a plugin that allows items to be overstacked (like more than 1 potion in 1 slot). CoreProtect doesn't rollback propoerly when this is the case. I tried to rollback a chest that had a stack of potions in 1 slot and it just filled every slot with potions and the other items are not retrievable

**Comment by Intelli** [comment]
Please provide steps to replicate.

**Comment by JHarris12345** [comment]
- Get an overstacked item (where you have more than the vanilla max stack size in 1 slot - like a stack of potions). You can do this via essentials or a plugin that allows overstacked items

- put them in chest

- have someone steal the stack

- rollback

- you will see that the chest rolls back incorrectly and instead of the stack taking up the 1 slot it was originally in, it spreads out over each slot

**Comment by Intelli** [comment]
Ah, what you're referring to is intentional, in that CoreProtect respects stack limits specified by the server when adding items to a chest.

CoreProtect does not track the initial stack sizes added by a player.
