### ISSUE TITLE
Crashes on canvasmc

### ISSUE THREAD

**Issue by pro9code** [PlayPro/CoreProtect#472]
[latest.log](https://github.com/PlayPro/CoreProtect/files/13460407/latest.log)

**Comment by Intelli** [comment]
> This server is running Canvas version git-Canvas-"c6e184e" (MC: 1.20.2) (Implementing API version Unknown-Version)

A valid version number is required.

**Comment by pro9code** [comment]
what is that?

**Comment by pro9code** [comment]
v22.2

**Comment by vacla** [comment]
@pro9code Canvas isn't sending a valid API version

**Comment by pro9code** [comment]
can you make an exception for canvas?
