### ISSUE TITLE
does not log chat log 1.20.1

### ISSUE THREAD

**Issue by BloodInAs** [PlayPro/CoreProtect#482]
does not log chat log 
1.20.1 minecraft
When trying to find the players' chat log, it does not give any result (screenshot)
<img width="613" alt="image" src="https://github.com/PlayPro/CoreProtect/assets/146227359/a0416403-31c7-47c7-8549-e02d2f888241">

**Comment by Intelli** [comment]
Unable to replicate

<img width="502" alt="image" src="https://github.com/PlayPro/CoreProtect/assets/6790859/0ffbfd01-f05d-45e9-ba5f-2333ba316404">

**Comment by Pipitkin** [comment]
> Unable to replicate
> 
> <img alt="image" width="502" src="https://private-user-images.githubusercontent.com/6790859/294340142-0ffbfd01-f05d-45e9-ba5f-2333ba316404.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDQ1NDgsIm5iZiI6MTcwNTUwNDI0OCwicGF0aCI6Ii82NzkwODU5LzI5NDM0MDE0Mi0wZmZiZmQwMS1mMDVkLTQ1ZTktYmE1Zi0yMzMzYmEzMTY0MDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTdUMTUxMDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjgzZDZlMDRjM2M2Mzk5ZDA4MTFmYzYyNGFjNTk1MzBlNmQ3NWQ1MTg5OTdiMTIyMTk5ZDE2YTYzODA1ZmU4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.V8TS_1E_e2tqSYTdsiJYObkzz0_57pRAxpkbiUXgZHY">

I have also this problem. I can't check logs for chat. Don't depends for other things (radius, user, etc.)
![image](https://github.com/PlayPro/CoreProtect/assets/139237587/90a5ce78-2755-46a5-962c-9bb2b908be86)
![image](https://github.com/PlayPro/CoreProtect/assets/139237587/8ccf8fe3-2ff5-4928-a168-ebb9d0f30805)

**Comment by Intelli** [comment]
> > Unable to replicate
> > <img alt="image" width="502" src="https://private-user-images.githubusercontent.com/6790859/294340142-0ffbfd01-f05d-45e9-ba5f-2333ba316404.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDQ1NDgsIm5iZiI6MTcwNTUwNDI0OCwicGF0aCI6Ii82NzkwODU5LzI5NDM0MDE0Mi0wZmZiZmQwMS1mMDVkLTQ1ZTktYmE1Zi0yMzMzYmEzMTY0MDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTdUMTUxMDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjgzZDZlMDRjM2M2Mzk5ZDA4MTFmYzYyNGFjNTk1MzBlNmQ3NWQ1MTg5OTdiMTIyMTk5ZDE2YTYzODA1ZmU4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.V8TS_1E_e2tqSYTdsiJYObkzz0_57pRAxpkbiUXgZHY">
> 
> I have also this problem. I can't check logs for chat. Don't depends for other things (radius, user, etc.) ![image](https://private-user-images.githubusercontent.com/139237587/297425886-90a5ce78-2755-46a5-962c-9bb2b908be86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MDUzNzAsIm5iZiI6MTcwNTcwNTA3MCwicGF0aCI6Ii8xMzkyMzc1ODcvMjk3NDI1ODg2LTkwYTVjZTc4LTI3NTUtNDZhNS05NjJjLTliYjJiOTA4YmU4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQyMjU3NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTU5NjUyYWFiYzlmNzdlMGM2MTFiOWJkZGY0ZTc0MmQwOWIwMTcxYjFmMGNlNWRiNDMzZTA5YjQzY2M5ZDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.10pxsLzJBc5km_SgYMmY-2PGATa4P1vpKGeJjgeVGdA) ![image](https://private-user-images.githubusercontent.com/139237587/297425991-8ccf8fe3-2ff5-4928-a168-ebb9d0f30805.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MDUzNzAsIm5iZiI6MTcwNTcwNTA3MCwicGF0aCI6Ii8xMzkyMzc1ODcvMjk3NDI1OTkxLThjY2Y4ZmUzLTJmZjUtNDkyOC1hMTY4LWViYjlkMGYzMDgwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQyMjU3NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzBkMjViZGRkMDNlNTViNTUyNWE2MzEzNGI4MjE2OWYzMzYyNGRhY2QxMTQ5ZWQ1N2IwN2EyZTFkNzUyNzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ks6LU0O7ZaaOrwBZ8Ae79E1Qh3w9GLi_RJY4xkywzvA)

Likely a conflicting plugin.
