### ISSUE TITLE
Translation DE/German

### ISSUE THREAD

**Issue by DasPotata** [PlayPro/CoreProtect#484]
I fixed your translation for the german lang file

# CoreProtect v22.2 Language Cache (de)

ACTION_NOT_SUPPORTED: "Diese Aktion wird nicht unterstützt."
AMOUNT_BLOCK: "{0} {Block|Blöcke}"
AMOUNT_CHUNK: "{0} {Chunk|Chunks}"
AMOUNT_ENTITY: "{0} {Entität|Entitäten}"
AMOUNT_ITEM: "{0} {Item|Items}"
API_TEST: "API-Test erfolgreich."
CACHE_ERROR: "WARNUNG: Fehler beim Validieren {0} Zwischenspeicher."
CACHE_RELOAD: "Erzwingen des Nachladens von {kartierung|welt} Caches aus der Datenbank."
CHECK_CONFIG: "Bitte überprüfe die config.yml"
COMMAND_CONSOLE: "Bitte führen Sie den Befehl von der Konsole aus."
COMMAND_NOT_FOUND: "Befehl \"{0}\" nicht gefunden."
COMMAND_THROTTLED: "Bitte warten Sie einen Moment und versuchen Sie es erneut."
CONSUMER_ERROR: "Verbraucherwarteschlange wird bereits verarbeitet {angehalten|fortgesetzt}."
CONSUMER_TOGGLED: "Die Verarbeitung der Verbraucherwarteschlange wurde durchgeführt {angehalten|fortgesetzt}."
CONTAINER_HEADER: "Containertransaktionen"
DATABASE_BUSY: "Datenbank beschäftigt. Bitte versuchen Sie es später erneut."
DATABASE_INDEX_ERROR: "Datenbankindizes können nicht validiert werden."
DATABASE_LOCKED_1: "Datenbank gesperrt. Warte bis zu 15 Sekunden..."
DATABASE_LOCKED_2: "Datenbank wird bereits verwendet. Bitte versuche es später erneut."
DATABASE_LOCKED_3: "Um die Datenbanksperre zu deaktivieren, setzen Sie \"database-lock: false\"."
DATABASE_LOCKED_4: "Das Deaktivieren der Datenbanksperre kann zu Datenbeschädigungen führen."
DATABASE_UNREACHABLE: "Datenbank ist nicht erreichbar. Daten verwerfen und herunterfahren."
DEVELOPMENT_BRANCH: "Entwicklungszweig erkannt, Patch-Skripte werden übersprungen."
DIRT_BLOCK: "Platziere einen Schmutzblock unter dir."
DISABLE_SUCCESS: "Erfolg! Deaktiviert {0}"
ENABLE_FAILED: "{0} war nicht in der Lage zu starten."
ENABLE_SUCCESS: "{0} ist jetzt aktiviert!"
ENJOY_COREPROTECT: "Dir gefällt {0}? Tritt unserem Discord bei!"
FINISHING_CONVERSION: "Abschluss der Datenkonvertierung. Bitte warten..."
FINISHING_LOGGING: "Abschluss der Datenprotokollierung. Bitte warten..."
FIRST_VERSION: "Anfangs-DB: {0}"
GLOBAL_LOOKUP: "Geben Sie keinen Radius an, um eine globale Suche durchzuführen."
GLOBAL_ROLLBACK: "Benutzen \"{0}\" um einen globalen {Rollback|Restore}"
HELP_ACTION_1: "Beschränken Sie die Suche auf eine Aktion."
HELP_ACTION_2: "Beispiele: [a:block], [a:+block], [a:-block] [a:click], [a:container], [a:inventory], [a:item], [a:kill], [a:chat], [a:command], [a:sign], [a:session], [a:username]"
HELP_COMMAND: "Zusätzliche Informationen anzeigen."
HELP_EXCLUDE_1: "Blöcke/Benutzer ausschließen."
HELP_EXCLUDE_2: "Beispiele: [e:stone], [e:Notch], [e:stone,Notch]"
HELP_HEADER: "{0} Hilfe"
HELP_INCLUDE_1: "Fügen Sie Blöcke/Entitäten ein."
HELP_INCLUDE_2: "Beispiele: [i:stone], [i:zombie], [i:stone,wood,bedrock]"
HELP_INSPECT_1: "Mit dem Inspector aktiviert, kannst du Folgendes tun:"
HELP_INSPECT_2: "Linksklick auf einen Block, um zu sehen, wer diesen Block platziert hat."
HELP_INSPECT_3: "Rechtsklick auf einen Block, um zu sehen, welcher benachbarte Block zerstört wurde."
HELP_INSPECT_4: "Einen Block platzieren, um zu sehen, welcher Block an dieser Stelle zerstört wurde."
HELP_INSPECT_5: "Einen Block in Flüssigkeit (etc.) platzieren, um zu sehen, wer sie platziert hat."
HELP_INSPECT_6: "Rechtsklick auf eine Tür, Truhe, etc., um zu sehen, wer sie zuletzt verwendet hat."
HELP_INSPECT_7: "Tipp: Du kannst einfach \"/co i\" verwenden, um schnelleren Zugriff zu erhalten."
HELP_INSPECT_COMMAND: "Schaltet den Blockinspektor um."
HELP_LIST: "Zeigt eine Liste aller Befehle an."
HELP_LOOKUP_1: "Befehlsverknüpfung."
HELP_LOOKUP_2: "Weitere Seiten anzeigen."
HELP_LOOKUP_COMMAND: "Blockdaten nachschlagen."
HELP_NO_INFO: "Informationen zum Befehl \"{0}\" nicht gefunden."
HELP_PARAMETER: "Bitte benutze \"{0}\" für detaillierte Parameterinformationen."
HELP_PARAMS_1: "Führe den {Lookup|Rollback|Restore} durch."
HELP_PARAMS_2: "Gib die Benutzer an, für die der {Lookup|Rollback|Restore} durchgeführt werden soll."
HELP_PARAMS_3: "Gib die Zeitspanne an, für die der {Lookup|Rollback|Restore} durchgeführt werden soll."
HELP_PARAMS_4: "Gib einen Radius an, um den {Lookup|Rollback|Restore} auf einen bestimmten Bereich zu beschränken."
HELP_PARAMS_5: "Beschränke den {Lookup|Rollback|Restore} auf eine bestimmte Aktion."
HELP_PARAMS_6: "Schließe bestimmte Blöcke/Entitäten in den {Lookup|Rollback|Restore} ein."
HELP_PARAMS_7: "Schließe Blöcke/Benutzer von dem {Lookup|Rollback|Restore} aus."
HELP_PURGE_1: "Alte Daten entfernen."
HELP_PURGE_2: "Beispiel: \"{0}\" löscht alle Daten, die älter als 30 Tage sind."
HELP_PURGE_COMMAND: "Alte Blockdaten löschen."
HELP_RADIUS_1: "Geben Sie einen Radiusbereich an."
HELP_RADIUS_2: "Beispiel: [r:10] (Nur Änderungen innerhalb von 10 Blöcken um dich herum vornehmen.)"
HELP_RELOAD_COMMAND: "Lädt die Konfigurationsdatei neu."
HELP_RESTORE_COMMAND: "Blockdaten wiederherstellen."
HELP_ROLLBACK_COMMAND: "Rollback-Blockdaten."
HELP_STATUS: "Sehen Sie sich den Plugin-Status an."
HELP_STATUS_COMMAND: "Zeigt den Plugin-Status an."
HELP_TELEPORT: "Teleportieren."
HELP_TIME_1: "Geben Sie die Uhrzeit an."
HELP_TIME_2: "Beispiele: [t:2w,5d,7h,2m,10s], [t:5d2h], [t:2.50h]"
HELP_USER_1: "Geben Sie die Benutzer an."
HELP_USER_2: "Beispiele: [u:Notch], [u:Notch,#enderman]"
INCOMPATIBLE_ACTION: "\"{0}\" kann mit dieser Aktion nicht verwendet werden."
INSPECTOR_ERROR: "Inspektor bereits {aktiviert|deaktiviert}."
INSPECTOR_TOGGLED: "Inspektor {aktiviert|deaktiviert}."
INTEGRATION_ERROR: "Unfähig zu {initialisieren|deaktivieren} {0} Protokollierung."
INTEGRATION_SUCCESS: "{0} erfolgreich anmelden {initialisiert|deaktiviert}."
INTEGRATION_VERSION: "Ungültig {0} Version gefunden."
INTERACTIONS_HEADER: "Spielerinteraktionen"
INVALID_ACTION: "Das ist keine gültige Aktion."
INVALID_BRANCH_1: "Ungültige Plugin-Version (Verzweigung wurde nicht gesetzt)."
INVALID_BRANCH_2: "Um fortzufahren, setzen Sie den Projektzweig auf \"Entwicklung\"."
INVALID_BRANCH_3: "Das Ausführen von Entwicklungscode kann zu Datenbeschädigungen führen."
INVALID_CONTAINER: "Bitte überprüfen Sie zuerst einen gültigen Behälter."
INVALID_DONATION_KEY: "Ungültiger Spendenschlüssel."
INVALID_INCLUDE: "\"{0}\" ist ein ungültiger Wert."
INVALID_INCLUDE_COMBO: "Das ist eine ungültige Typenkombination."
INVALID_RADIUS: "Bitte geben Sie einen gültigen Radius ein."
INVALID_SELECTION: "{0} Auswahl nicht gefunden."
INVALID_USERNAME: "\"{0}\" ist ein ungültiger Benutzername."
INVALID_WORLD: "Bitte geben Sie eine gültige Welt an."
LATEST_VERSION: "Neueste Version: {0}"
LINK_DISCORD: "Discord: {0}"
LINK_DOWNLOAD: "Herunterladen: {0}"
LINK_PATREON: "Patreon: {0}"
LINK_WIKI_BLOCK: "Blocknamen: {0}"
LINK_WIKI_ENTITY: "Entitätsnamen: {0}"
LOGGING_ITEMS: "{0} Elemente, die noch zu loggen sind. Warten Sie mal..."
LOGGING_TIME_LIMIT: "Zeitlimit für die Protokollierung erreicht. Daten verwerfen und herunterfahren."
LOOKUP_BLOCK: "{0} {platziert|entfernt} {1}."
LOOKUP_CONTAINER: "{0} {hinzugefügt|entfernt} {1} {2}."
LOOKUP_HEADER: "{0} Ergebnisse"
LOOKUP_INTERACTION: "{0} {angeklickt|getötet} {1}."
LOOKUP_ITEM: "{0} {aufgehoben|abgeworfen} {1} {2}."
LOOKUP_LOGIN: "{0} {ein|aus}geloggt."
LOOKUP_PAGE: "Seite {0}"
LOOKUP_PROJECTILE: "{0} {geworfen|geschossen} {1} {2}."
LOOKUP_ROWS_FOUND: "{0} {Reihe|Reihen} gefunden."
LOOKUP_SEARCHING: "Suche nachschlagen. Warten Sie mal..."
LOOKUP_STORAGE: "{0} {hinterlegt|abgehoben} {1} {2}."
LOOKUP_TIME: "Vor {0}"
LOOKUP_USERNAME: "{0} Eingeloggt als {1}."
MAXIMUM_RADIUS: "Das Maximum {Nachschlagen|Rollback|Wiederherstellen} Radius ist {0}."
MISSING_ACTION_USER: "Um diese Aktion zu verwenden, geben Sie bitte einen Benutzer an."
MISSING_LOOKUP_TIME: "Bitte geben Sie die Zeit an, um {Nachschlagen|Rollback|Wiederherstellen}."
MISSING_LOOKUP_USER: "Bitte geben Sie einen Benutzer an oder {Block|Radius}."
MISSING_PARAMETERS: "Bitte verwenden Sie \"{0}\"."
MISSING_ROLLBACK_RADIUS: "Sie haben nicht angegeben a {Zurücksetzen|Wiederherstellen} Radius."
MISSING_ROLLBACK_USER: "Sie haben nicht angegeben a {Zurücksetzen|Wiederherstellen} Benutzer."
MYSQL_UNAVAILABLE: "Verbindung zu nicht möglich MySQL Server."
NETWORK_CONNECTION: "Verbindung durch {0} {erfolgreich|fehlgeschlagen}. Benutzen {1} {2}."
NETWORK_TEST: "Die Netzwerktestdaten wurden erfolgreich gesendet."
NO_DATA: "Keine Daten gefunden bei {0}."
NO_DATA_LOCATION: "Keine {Daten|Transaktionen|Interaktionen|Nachrichten} gefunden."
NO_PERMISSION: "Du hast keine Erlaubnis das zu tun."
NO_RESULTS: "Keine Ergebnisse gefunden."
NO_RESULTS_PAGE: "Keine {Ergebnisse|Daten} für diese Seite gefunden."
NO_ROLLBACK: "Nein {ausstehend|zurück} Rollback/Wiederherstellung gefunden."
PATCH_INTERRUPTED: "Upgrade unterbrochen. Werde es beim Neustart nochmal versuchen."
PATCH_OUTDATED_1: "Datenbanken, die älter als sind, können nicht aktualisiert werden {0}."
PATCH_OUTDATED_2: "Bitte aktualisieren Sie mit einer unterstützten Version von CoreProtect."
PATCH_PROCESSING: "Verarbeitung neuer Daten. Warten Sie mal..."
PATCH_SKIP_UPDATE: "Überspringen {Tabelle|Index} {Aktualisieren|Erstellen|Entfernen} auf {0}."
PATCH_STARTED: "Performing {0} Aktualisierung. Warten Sie mal..."
PATCH_SUCCESS: "Erfolgreich aktualisiert auf {0}."
PATCH_UPGRADING: "Datenbank-Upgrade im Gange. Warten Sie mal..."
PLEASE_SELECT: "Bitte auswählen: \"{0}\" oder \"{1}\"."
PREVIEW_CANCELLED: "Vorschau abgebrochen."
PREVIEW_CANCELLING: "Vorschau abbrechen..."
PREVIEW_IN_GAME: "Sie können Rollbacks nur im Spiel in der Vorschau anzeigen."
PREVIEW_TRANSACTION: "Sie können keine Vorschau anzeigen {Behälter|Inventar} Transaktionen."
PURGE_ABORTED: "Bereinigung fehlgeschlagen. Die Datenbank ist möglicherweise beschädigt."
PURGE_ERROR: "Kann nicht verarbeitet werden {0} Daten!"
PURGE_FAILED: "Bereinigung fehlgeschlagen. Bitte versuchen Sie es später erneut."
PURGE_IN_PROGRESS: "Bereinigung läuft. Bitte versuchen Sie es später erneut."
PURGE_MINIMUM_TIME: "Sie können nur Daten löschen, die älter sind als {0} {Tage|Stunden}."
PURGE_NOTICE_1: "Bitte beachten Sie, dass dies einige Zeit dauern kann."
PURGE_NOTICE_2: "Starten Sie Ihren Server nicht neu, bis dies abgeschlossen ist."
PURGE_OPTIMIZING: "Optimierung der Datenbank. Warten Sie mal..."
PURGE_PROCESSING: "wird bearbeitet {0} Daten..."
PURGE_REPAIRING: "Versuch einer Reparatur. Dies könnte eine Weile dauern..."
PURGE_ROWS: "{0} {Reihe|Reihen} von Daten gelöscht."
PURGE_STARTED: "Datenbereinigung gestartet am \"{0}\"."
PURGE_SUCCESS: "Datenbereinigung erfolgreich."
RELOAD_STARTED: "Konfiguration wird neu geladen - bitte warten."
RELOAD_SUCCESS: "Konfiguration neu geladen."
ROLLBACK_ABORTED: "Rollback oder Wiederherstellung abgebrochen."
ROLLBACK_CHUNKS_FOUND: "{0} {bearbeiteter|bearbeitete} {Chunk|Chunks} gefunden."
ROLLBACK_CHUNKS_MODIFIED: "{0}/{1} {Chunk|Chunks} bearbeitet."
ROLLBACK_COMPLETED: "{Rollback|Wiederherstellen|Vorschau} abgeschlossen für \"{0}\"."
ROLLBACK_EXCLUDED_USERS: "Ausgeschlossen {Benutzer|Benutzer}: \"{0}\"."
ROLLBACK_INCLUDE: "{Eingeschlossen|Ausgeschlossen} {Block|Entität|Ziel} {Typ|Typen}: \"{0}\"."
ROLLBACK_IN_PROGRESS: "Ein Rollback/Restore ist bereits im Gange."
ROLLBACK_LENGTH: "Zeit beansprucht: {0} {Sekunde|Sekunden}."
ROLLBACK_MODIFIED: "{Modifiziert|Modifiziert} {0}."
ROLLBACK_RADIUS: "Radius: {0} {Block|Blöcke}."
ROLLBACK_SELECTION: "Radius eingestellt auf \"{0}\"."
ROLLBACK_STARTED: "{Rollback|Wiederherstellen|Vorschau} gestartet für \"{0}\"."
ROLLBACK_TIME: "Zeitspanne: {0}."
ROLLBACK_WORLD_ACTION: "Beschränkt auf {Welt|Aktion} \"{0}\"."
SIGN_HEADER: "Nachrichten signieren"
STATUS_CONSUMER: "Warteschleife: {0} {Datensatz|Datensätze}"
STATUS_DATABASE: "Datenbank: {0}"
STATUS_INTEGRATION: "{0}: Integration {aktiviert|deaktiviert}."
STATUS_LICENSE: "Lizenz: {0}"
STATUS_VERSION: "Version: {0}"
TELEPORTED: "Teleportiert nach {0}."
TELEPORTED_SAFETY: "Hab dich in Sicherheit teleportiert."
TELEPORT_PLAYERS: "Der Teleport-Befehl kann nur von Spielern verwendet werden."
TIME_DAYS: "{0} {Tag|Tage}"
TIME_HOURS: "{0} {Stunde|Stunden}"
TIME_MINUTES: "{0} {Minute|Minuten}"
TIME_SECONDS: "{0} {Sekunde|Sekunden}"
TIME_WEEKS: "{0} {Woche|Wochen}"
UPDATE_ERROR: "Beim Suchen nach Updates ist ein Fehler aufgetreten."
UPDATE_HEADER: "{0} Aktualisieren"
UPDATE_NOTICE: "Beachten: {0} ist nun verfügbar."
UPGRADE_IN_PROGRESS: "Upgrade läuft. Bitte versuchen Sie es später erneut."
USER_NOT_FOUND: "Benutzer \"{0}\" nicht gefunden."
USER_OFFLINE: "Der Benutzer \"{0}\" ist nicht online."
USING_MYSQL: "Verwenden von MySQL zur Datenspeicherung."
USING_SQLITE: "Verwenden von SQLite zur Datenspeicherung."
VALID_DONATION_KEY: "Gültiger Spendenschlüssel."
VERSION_NOTICE: "Ausführung {0} ist nun verfügbar."
VERSION_REQUIRED: "{0} {1} oder höher erforderlich."
WORLD_NOT_FOUND: "Welt \"{0}\" nicht gefunden."

**Comment by Intelli** [comment]
The file you pasted here is missing the backslashes.

Please submit a PR (clone the repo, then modify this file: https://github.com/PlayPro/CoreProtect/blob/master/lang/de.yml)
