### ISSUE TITLE
Death Logs

### ISSUE THREAD

**Issue by RealmKebab** [PlayPro/CoreProtect#485]
So you see, there are already kill logs, which display what entity or user a player has killed in a specified amount of time. It'd be pretty good for admins to have death logs, which display what entity or user has killed the player before in a specified amount of time.

I recommend this because it's a pain trying to find who killed who checking kill logs since the entire server I moderate use Blaze farms way too much.

**Comment by Intelli** [comment]
Player deaths are already logged.

**Comment by RealmKebab** [comment]
> Player deaths are already logged.

have you even read what i've said
