### ISSUE TITLE
Obfuscation (§k) in item names ore lore causes unreadable item in lookup

### ISSUE THREAD

**Issue by ByteExceptionM** [PlayPro/CoreProtect#487]
If the item name or the lore contains obfuscation (§k), the **entire** item is no longer readable.

![image](https://github.com/PlayPro/CoreProtect/assets/47250043/0f5ef452-1f9b-4cb8-97e1-71cef8d82ac7)

![image](https://github.com/PlayPro/CoreProtect/assets/47250043/12d56035-d842-455e-ae33-72b67cc78b9d)

**Comment by U5B** [comment]
This is because reset color codes are not properly parsed.
