### ISSUE TITLE
Cannot modify world on 1.20.4

### ISSUE THREAD

**Issue by TheKrafter** [PlayPro/CoreProtect#488]
**NOTE: I am aware that 1.20.4 is not officially supported yet, I just want yall to be aware of this and aid in the upgrade process**

When trying to restore parts of a world, CoreProtect claims to have properly restored the world:

![image](https://github.com/PlayPro/CoreProtect/assets/75903664/962d653b-49b8-49a5-b83b-4db28550905f)

However, the world itself is not actually changed.

There are no errors (or other messages) in the console regarding this whatsoever.

**Comment by Intelli** [comment]
Please provide the inspector output of a block you’re trying to restore, as well as your server log.

**Comment by TheKrafter** [comment]
A block I'm tryna restore:
![CoreProtect: 1.84 days ago RevanEnlightened placed white_bed](https://github.com/PlayPro/CoreProtect/assets/75903664/a1d20848-d01c-4a0e-922a-bd46432f5126)

And latest.log: https://mclo.gs/0fgz1UN

**Comment by TheKrafter** [comment]
Also of note: this world did have a strange issue where these blocks disappeared, however I restored this region of the world from a backup that happened before the issue.

However from my understanding, the restore action should be able to replace these blocks regardless of whether it has logged that they were removed.

**Comment by Intelli** [comment]
Sounds like you have some sort of corruption bug going on that isn't related to CoreProtect.
