### ISSUE TITLE
incorrect behavior with hopper transfer event

### ISSUE THREAD

**Issue by AndreyKrasnov06** [PlayPro/CoreProtect#489]
The Coreprotect plugin was adding thousands of "hopper moved air" messages to the database every second, which caused the plugin to hang and load the processor due to the constant change of the database.

Solution:
disable hopper transfer event

plugins:
core protect

Server:
kaiiju
folia
i created empty folia server to retest the issue

**Comment by Intelli** [comment]
> i created empty folia server to retest the issue

Please provide steps to replicate.

**Comment by Intelli** [comment]
Tested on an "empty folia server", and was unable to replicate any issues.

Hopper logging appears to be functioning normally when tested.

**Comment by AndreyKrasnov06** [comment]
I've built [https://www.youtube.com/watch?v=LPshwkDboXk&t=205s&pp=ygUKY2FydCBtaXMgMg%3D%3D] on empty folia server and fill resources into this. after few minutes, i see the colossal database queue (/co status - 180000 in queue). I understand that this bug is quite difficult to reproduce, but it began to haunt us when players began to build large auto-sorting systems. Perhaps it’s worth at least guessing what the problem might be in order to avoid such surprises from the plugin

**Comment by Intelli** [comment]
Please provide a copy of the world folder.
