### ISSUE TITLE
Shulker Colors combined in 1 group [SUGGESTION]

### ISSUE THREAD

**Issue by Tosfoy** [PlayPro/CoreProtect#493]
There should be a way to lookup all shulker colors by using 1 pre-made group text
For example
/co lookup u:Tosfoy t:3d b:#shulker_box

**Comment by Intelli** [comment]
Implemented in https://github.com/PlayPro/CoreProtect/commit/377a6f55b94fde89ca1cf003972910fac69fc3fe
