### ISSUE TITLE
WorldEdit (FAWE) support doesn't work

### ISSUE THREAD

**Issue by trushniuser** [PlayPro/CoreProtect#496]
WorldEdit (FAWE) support doesn't work in the latest version v22.2 with latest FAWE build 646 in 1.20.4

Video: https://imgur.com/p6Uw5Vh

**Comment by Legoman99573** [comment]
Can confirm even when adding ``net.coreprotect.worldedit.CoreProtectLogger`` to the ``extent.allowed-plugins`` list in ``config.yml``

**Comment by Telesphoreo** [comment]
Can confirm latest FAWE builds for at least a month now haven't been logging with CoreProtect

**Comment by rand0m0User** [comment]
just tried with the "latest" build (FastAsyncWorldEdit-Bukkit-2.9.1-SNAPSHOT-672.jar) and its broken still, showing "no data" after a //replacenear operation, funny that nobody else is complaining about it on FAWE's github that some compatibility is broken

**Comment by Deauthorized** [comment]
Whenever this situation arises the two developers go into a loop of "Nah they need to fix it on their end" instead of just taking initiative themselves.

**Comment by Deauthorized** [comment]
On the latest snapshot that I have "FastAsyncWorldEdit-Bukkit-2.9.2-SNAPSHOT-709" any operations done via command (//sphere) are logged fine, but edits via the wand are not.

**Comment by Deauthorized** [comment]
Found the commit which broke logging: https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/28ab5662fdb72f1bf6eb2abbd2127ee24b4e9635

**Comment by Goinging** [comment]
I am pretty sure this also break //undo, I may just be dumb but when I made a mistake and tried //undoing it didn’t save the entities or biomes of the area.

**Comment by Telesphoreo** [comment]
I have fixed the issue. You can download a fixed jar here until it is merged and released: https://s3.telesphoreo.me/coreprotect/CoreProtect-fork-22.2-v22.2-16-gc4350bb.dirty.jar
