### ISSUE TITLE
Purge parameters that are ran on startup

### ISSUE THREAD

**Issue by Telesphoreo** [PlayPro/CoreProtect#497]
With Prism (another rollback plugin), when you start up the server, it runs a list of parameters set in the config to purge the database. The default is to purge anything older than 2 months automatically and it is ran every time the server starts up. I think it would be a great addition to CoreProtect as I wouldn't have to take the server down for hours every month to purge the data and then optimize the tables. I feel like it would help server owners keep disk usage under control a lot easier

**Comment by Intelli** [comment]
The CoreProtect purge command can be ran while the server is in use.

**Comment by Telesphoreo** [comment]
I know, but I'd love there to be an option to do it on start up like Prism. It's not practical to run it in game due to the fact that our server is busy and the queue can get huge.

**Comment by Intelli** [comment]
Duplicate of #176
