### ISSUE TITLE
Almost all storage taken up by CoreProtect suddenly

### ISSUE THREAD

**Issue by JunglTemple** [PlayPro/CoreProtect#498]
I was using the inspector to see who mined into somebody's house on my server, when suddenly a bunch of errors started appearing in the console, so fast I couldn't read them. Then, all of the players got timed out and the server had crashed. Pterodactyl tried auto-restarting but then I got an error saying that there was not enough free space left to start. I had to enter FTP, and found that the CoreProtect database file was taking up almost 5 gigabytes. This was a problem, as that was the maximum amount provided by my free hosting provider. I deleted the database and after a restart, the server _did_ launch, but half of my plugins' configs got reset, player balances got reset, advancements, etc. I can't even get access to the log because that got deleted, too. I have no idea what the problem was, but it was probably related to CoreProtect in some way (it _did_ start appearing in exceptions).

**Comment by Intelli** [comment]
... when did you install CoreProtect?

**Comment by JunglTemple** [comment]
> ... when did you install CoreProtect?

I installed it... probably about a year ago.
