### ISSUE TITLE
Wrong teleport location on lookup result with large coordinates

### ISSUE THREAD

**Issue by radiant-ai** [PlayPro/CoreProtect#499]
CoreProtect teleports to wrong location when attempted to do so on very large coordinates (10,000,000+).

Using:
![image](https://github.com/PlayPro/CoreProtect/assets/43506080/c1f6e9a6-e10c-4b3f-bc8e-ff197e14aae2)

Reproduction steps:
1. Teleport far away from world center (`/tp @a 10000010 100 5`).
2. Place a block.
3. Do a lookup (`/co l radius:5 action:block time:1h`).
4. Click on chat component with teleport:
![image](https://github.com/PlayPro/CoreProtect/assets/43506080/f9d4d695-ece5-447e-9510-325ffb8d17b9)
5. Notice wrong teleport location.

If we try to use large negative coordinates (e.g. `/tp @a -10000010 100 5`) the teleportation stops working completely:

![image](https://github.com/PlayPro/CoreProtect/assets/43506080/acaaa11a-976b-429a-b7b6-dcedffcdb727)

I think something wrong happens when CoreProtect builds clickable chat component.

**Comment by Intelli** [comment]
Duplicate of #322 / #491
