### ISSUE TITLE
Large MySQL

### ISSUE THREAD

**Issue by WarpedDoctor** [PlayPro/CoreProtect#501]
Within the past week, My MySQL Core Protect database has gone from 30-40GB to over 770 GB.

During this period, we have had 2 players log onto the server. So I feel this is an error/ bug.

**Comment by Intelli** [comment]
What data is being logged? And please provide your server/plugin information.

**Comment by WarpedDoctor** [comment]
> What data is being logged? And please provide your server/plugin information.

All Player things are logged. Nothing natural/Redstone related.

1.19.4 Paper server. plugin Coreprotect latest version, Others incase wanted:

WorldEdit, Shopkeepers, Brewery, Citizens, Dead Chests, Power Portals, Terraform Generator, Inv Rollback, Dynmap, Clearlagg.
