### ISSUE TITLE
[Feature] Auto purge some actions depending on delay

### ISSUE THREAD

**Issue by WarnDa** [PlayPro/CoreProtect#503]
Hello,

Some servers use CoreProtect just for some prevention again place/break of players in the past week (to see abuse), but still need to log some more important other things londer

So it would be nice to get a way to determine the delay of log of action/blocks.
For example cobblestone place/break could be log 48hr, diamond_ore 15 days, and chat or commands 1-2 months

**Comment by Intelli** [comment]
Duplicate of #176 

Please comment there if there's additional functionality you'd like to see in that suggestion.
