### ISSUE TITLE
bug coreprotect

### ISSUE THREAD

**Issue by Savranchuk** [PlayPro/CoreProtect#505]
The player placed a barrel. (Private created by LWC PLUGIN), another player places rails and a trolley with a funnel under it. The log is visible, we do a rollback, but it doesn’t happen. Vulture, vulture, but the rollback is not done, and we don’t know why and how

**Comment by Intelli** [comment]
Unable to replicate

<img width="542" alt="image" src="https://github.com/PlayPro/CoreProtect/assets/6790859/db9c72b5-ee71-4730-a20f-8eecda7d1e2e">

Please ensure you're either using a rollback command that targets all users, or target the #hopper user.
