### ISSUE TITLE
Failed to execute goal

### ISSUE THREAD

**Issue by Justman100** [PlayPro/CoreProtect#508]
Get this, if i try to compile

> Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.2.4:shade (default) on project CoreProtect: Execution default of goal org.apache.maven.plugins:maven-shade-plugin:3.2.4:shade failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-shade-plugin:3.2.4:shade: java.lang.NoSuchMethodError: 'java.lang.Object org.apache.maven.model.Plugin.getGoals()'

**Comment by NedHuman** [comment]
doesnt CoreProtect use gradle instead of maven?

**Comment by Justman100** [comment]
> doesnt CoreProtect use gradle instead of maven?

It exists a _.pom_ and no _gradlew_ file

**Comment by Justman100** [comment]
@Intelli

**Comment by Justman100** [comment]
@Intelli
