### ISSUE TITLE
[Suggestion] Ability to cancel an ongoing rollback/lookup

### ISSUE THREAD

**Issue by NedHuman** [PlayPro/CoreProtect#524]
Currently /co cancel only works on rollbacks which haven't started. It would be very useful for servers with large databases to cancel an ongoing rollback/lookup.

**Comment by NedHuman** [comment]
Fr wth, 10 minute lookup taking eons

**Comment by Intelli** [comment]
Lookups and rollbacks should typically only take a couple seconds. If lookups/rollbacks/restores are taking a significant amount of time, or your database is repeatedly stating it's busy, you make have some other issue going on, such as extremely slow IO speeds.

If a command is repeatedly providing slow lookup times for you, please provide the exact command, so I can investigate further.
