### ISSUE TITLE
Disable Logging does not work

### ISSUE THREAD

**Issue by egssens** [PlayPro/CoreProtect#534]
My core inspect is getting too big with afk miners + hoppers. I need to disable logging of stone but it does not work.

blacklist.txt
minecraft:stone

https://docs.coreprotect.net/config/#disabling-logging

**Comment by Intelli** [comment]
CoreProtect v22.3+ is required.

**Comment by leogianfagna** [comment]
> CoreProtect v22.3+ is required.

@Intelli 
![image](https://github.com/PlayPro/CoreProtect/assets/142264317/b8a13f3d-31a2-4166-9616-3297d5734ccd)
![image](https://github.com/PlayPro/CoreProtect/assets/142264317/74c6a00f-bb5b-49e2-bedf-6496fcc04659)

This doesn't worked.

**Comment by Intelli** [comment]
* CoreProtect Edge v22.3
