### ISSUE TITLE
Improve CoreProtect API

### ISSUE THREAD

**Issue by mikinol** [PlayPro/CoreProtect#544]
I would like to suggest improving the CoreProtect API.

My proposal is to extend the functionality of the events available through the CoreProtect API. The essence of my proposal is to enrich events with more detailed information about the logs (where and what block was placed or an item was taken) and to introduce separate events for different types of logs.

I look forward to your thoughts on this proposal.

**Comment by Intelli** [comment]
Can you please clarify the exact functionality you'd like added, with examples of how this functionality would be used in another plugin?
