### ISSUE TITLE
[Suggestion] Logging of /execute commands

### ISSUE THREAD

**Issue by ItsLeon15** [PlayPro/CoreProtect#547]
There should be a way to rollback actions that have occurred from an /execute command as at the moment whatever happens you can't roll it back. This could be particularly useful when an attacker gains access to OP, runs this command and destroys your server.

**Comment by Intelli** [comment]
Please provide examples of exactly what you'd like to see logged with this command.

**Comment by ItsLeon15** [comment]
Commands like `/execute run <command>` could report the specific command and argument that was used on lookup. Commands used from `/execute` that affect block updates such as `replacenear` / `fill` / `remove` would be the most important where you can rollback the command which undo's the block changes when doing `/co rollback a:command`.

Or add the changed blocks that was caused by these commands to be logged in the normal way and just be able to `/co rollback r:10 t:1d` which includes the blocks modified by the `/execute` command.

**Comment by Intelli** [comment]
Added on new suggestions here: https://github.com/PlayPro/CoreProtect/issues/237#issuecomment-2174349972

**Comment by ItsLeon15** [comment]
Thanks!
