### ISSUE TITLE
NPE on v22.4

### ISSUE THREAD

**Issue by Shepelzz** [PlayPro/CoreProtect#548]
Testing is a joke for you, yeah?

![image](https://github.com/PlayPro/CoreProtect/assets/38551207/40b29d15-ad18-4742-87e4-94611448cb47)

**Comment by vacla** [comment]
@Shepelzz Can you sent the full log here?

**Comment by Shepelzz** [comment]
[latest.log](https://github.com/PlayPro/CoreProtect/files/15469566/latest.log)

**Comment by vacla** [comment]
Seems to be fixed in next version already, see: https://github.com/PlayPro/CoreProtect/commit/5242973fe8749fa09b4e8a0621e89bee715687be

**Comment by Intelli** [comment]
Already fixed here: https://github.com/PlayPro/CoreProtect/commit/cfb53f766e9fcc661b6c26d118e3566c6c07334c

**Comment by tticehurst** [comment]
I have 22.4 installed I still get this error message

**Comment by vacla** [comment]
@tticehurst that is normal as it will be fixed in next version

**Comment by tticehurst** [comment]
> Seems to be fixed in next version already, see: [5242973](https://github.com/PlayPro/CoreProtect/commit/5242973fe8749fa09b4e8a0621e89bee715687be)

I assumed by this comment that it was in the already released version from around the date of this commit. My mistake

**Comment by tticehurst** [comment]
Also same errors for inventoryClickEvent and InventoryMoveEvent

**Comment by agoniaprivat** [comment]
Same issue here running Coreprotect Edge 23.0-rc1

**Comment by Intelli** [comment]
> Same issue here running Coreprotect Edge 23.0-rc1

Almost certainly a different error. Please post your log.
