### ISSUE TITLE
Spam In Logs When Breaking A Block

### ISSUE THREAD

**Issue by yunus-cakir** [PlayPro/CoreProtect#556]
Hi! My server always sends me when anyone tries to break a block. What should I do? I would really appreciate it if you could help me.
[STDERR]: java.lang.NullPointerException: Cannot invoke "org.bukkit.block.data.BlockData.getAsString()" because the return value of "net.coreprotect.utility.Util.createBlockData(org.bukkit.Material)" is null
[STDERR]:  at net.coreprotect.utility.Util.stringToByteData(Util.java:497)
[STDERR]:  at net.coreprotect.database.statement.BlockStatement.insert(BlockStatement.java:16)
[STDERR]:  at net.coreprotect.database.logger.BlockBreakLogger.log(BlockBreakLogger.java:69)
[STDERR]:  at net.coreprotect.consumer.process.BlockBreakProcess.process(BlockBreakProcess.java:24)
[STDERR]:  at net.coreprotect.consumer.process.Process.processConsumer(Process.java:145)
[STDERR]:  at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[STDERR]:  at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by Intelli** [comment]
Without additional information, I would guess you’re running some sort of unsupported server software.
