### ISSUE TITLE
Rollback does not work when inventory is full

### ISSUE THREAD

**Issue by mikinol** [PlayPro/CoreProtect#559]
When you try to roll back resources to a player with a full inventory, the resources disappear, although everything is fine in the logs
I suggest simply throwing items on the ground if the player doesn't have room in their inventory.

**Comment by Intelli** [comment]
This is intended behavior, and will never be an issue with a standard rollback command based off the current state.

For example:
`/co rollback a:inventory t:30m u:username`

Inventory rollbacks both remove and add items, so dropping items on the ground could result in item duplication.
