### ISSUE TITLE
Herochat integration?

### ISSUE THREAD

**Issue by AiKillerTV** [PlayPro/CoreProtect#56]
I was wondering if yall would integrate with Herochat, when I use Herochat with CoreProtect it gets logged under commands if the user uses the shortcut to talk in that channel for example global chat /g (message). I would like it to show up in the chat log instead of the command log.

**Comment by Intelli** [comment]
As that's a command, having it logged under commands should remain the default behaviour.

This behaviour can be modified though by utilizing CoreProtect's API. Commands could be logged as chat messages by utilizing the `logChat` method: https://docs.coreprotect.net/api/#available-methods

This could either be done on Herochat's end if they wanted, or via a separate plugin.
