### ISSUE TITLE
The console spams the problem and the ping is rising. magma core version 1.20.1

### ISSUE THREAD

**Issue by aktosezz** [PlayPro/CoreProtect#562]
Here is the error itself in the screenshot.
the core  magma 1.20.1
![2024-06-17_23-57-37](https://github.com/PlayPro/CoreProtect/assets/172500612/e15fc4ec-8146-4c49-b0b6-3d7758d34b66)

**Comment by aktosezz** [comment]
ping is very rising

**Comment by Intelli** [comment]
Duplicate of #548

Fixed here: https://github.com/PlayPro/CoreProtect/commit/cfb53f766e9fcc661b6c26d118e3566c6c07334c

**Comment by aktosezz** [comment]
i am sorry i don't understand english well what should I do with this?

**Comment by Intelli** [comment]
The fix will be included in the next release.

A temporary solution is to set
`hopper-transactions: false` in config.yml
