### ISSUE TITLE
Logs are not saved

### ISSUE THREAD

**Issue by BAD7777** [PlayPro/CoreProtect#564]
Hi. With the latest changes in barrels, shulkers and other containers, some things are not saved. For example: an emerald.
![image](https://github.com/PlayPro/CoreProtect/assets/129652614/333e9332-74d9-4a69-9489-a4ce018b39f6)
![image](https://github.com/PlayPro/CoreProtect/assets/129652614/20e7e010-0035-44f2-b35c-a276c64a464a)
When moving objects in the barrel, they appear in the logs.

**Comment by Intelli** [comment]
Unable to replicate an issue

<img width="629" alt="image" src="https://github.com/PlayPro/CoreProtect/assets/6790859/92d983f5-cf15-488f-8770-2a064d48904e">

**Comment by Intelli** [comment]
> Could not pass event InventoryDragEvent to CoreProtect v22.4 java.lang.IncompatibleClassChangeError: Found class org.bukkit.inventory.InventoryView, but interface was expected at CoreProtect-22.4.jar/net.coreprotect.listener.player.InventoryChangeListener.onInventoryDragEvent(InventoryChangeListener.java:293) ~[CoreProtect-22.4.jar:?] at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-2233-0d6766e] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?] at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:481) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e] at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:383) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e] at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3197) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e] at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e] at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e] at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e] at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e] at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e] at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1546) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e] at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e] at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1523) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e] at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1446) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e] at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e] at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1412) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1273) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e] at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

Purpur issue / you need to update your Purpur server.

**Comment by Intelli** [comment]
> Checking version, please wait... Current Purpur Version: 1.20.6-2233-0d6766e (MC: 1.20.6) You are running the latest version Previous: 1.20.6-2232-f1c87e4 (MC: 1.20.6)

Purpur stated they won't fix the 1.20.6 version, and you can use a 1.21 build from here: https://purpurmc.org/downloads/1.21

So I guess if you want a functional 1.20.6 build, you'll need to use Paper.
