### ISSUE TITLE
1.21 changes InventoryView from an abstract class to an interface

### ISSUE THREAD

**Issue by CyberFlameGO** [PlayPro/CoreProtect#567]
Title; produces 
```
java.lang.IncompatibleClassChangeError: Found class org.bukkit.inventory.InventoryView, but interface was expected
    at CoreProtect-22.4.jar//net.coreprotect.listener.player.InventoryChangeListener.onInventoryClick(InventoryChangeListener.java:254)
```
when running on versions less than 1.21

**Comment by Intelli** [comment]
Purpur issue, resolved in the latest Purpur 1.21 builds.

**Comment by CyberFlameGO** [comment]
No I'm on Purpur 1.20.6

**Comment by Intelli** [comment]
Yes, and it’s fixed in the 1.21 builds

**Comment by CyberFlameGO** [comment]
My bad there - I meant that (from [Spigot's git commit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/d01c70e93ea1018048a433717c46120eaaeda5ab#src%2Fmain%2Fjava%2Forg%2Fbukkit%2Fcraftbukkit%2Futil%2FCommodore.java)) it looks like the code won't work on any servers with a lower version than 1.21 which is why I created the issue (unless that's out of scope)

**Comment by Intelli** [comment]
The issue isn’t something that can be fixed by CoreProtect.

Options are to use Purpur 1.21, or use Paper 1.20.6

**Comment by CyberFlameGO** [comment]
Ah alrighty
