### ISSUE TITLE
Windcharges add "#explosion broke X block" log

### ISSUE THREAD

**Issue by WaffleDevs** [PlayPro/CoreProtect#579]
Title.

Images are 80 pages of  explosion logs. Someone had fun with the new windcharges.

![image](https://github.com/PlayPro/CoreProtect/assets/77215539/d87abd0a-9e89-4ab7-83ef-c20f00b9053e)
![image](https://github.com/PlayPro/CoreProtect/assets/77215539/ac9fded0-fee6-4d62-ac1e-9eeb6782e31f)

**Comment by WaffleDevs** [comment]
Only thing I could recommend is have it only log on blocks that it actually effects.

**Comment by Intelli** [comment]
Already fixed in [CoreProtect v23](https://www.patreon.com/posts/coreprotect-edge-106822813)
