### ISSUE TITLE
Rolled back a area and the items didn't return to the chests

### ISSUE THREAD

**Issue by itsBeaco** [PlayPro/CoreProtect#58]
I recently had a little bit of grief on my server. I rolled back an area and the items didn't return to the chests but on the logs, it knows the items should be there. Is there anything that could be affecting this or is there a known issue? I'm up to date with Core Protect 20.0 

![image](https://user-images.githubusercontent.com/77558094/127079990-47a7a892-231a-4181-a024-96d5bae38cb5.png)

![image](https://user-images.githubusercontent.com/77558094/127080018-c3fce464-c9b2-46be-a393-a6edbb718493.png)

**Comment by Intelli** [comment]
Please check your server log for any errors.

As well, please try running `/co restore`, and then re-running `/co rollback`

**Comment by itsBeaco** [comment]
Issue resolved with the 20.1 update :) Not really sure what happened there but everything is good now. Thank you for getting back to me about it!

**Comment by Intelli** [comment]
Ah perfect, thanks for the update!
