### ISSUE TITLE
Could not pass event ProjectileLaunchEvent on 1.21

### ISSUE THREAD

**Issue by StKillReal** [PlayPro/CoreProtect#580]
![image](https://github.com/PlayPro/CoreProtect/assets/60330193/c8d4ca31-dab5-4e7e-a66e-cd3f62e444a7)
https://mclo.gs/NLOTN02

**Comment by Intelli** [comment]
Error log is a duplicate issue / fixed in v23

However, your error log you posted also doesn’t include anything about the ProjectileLaunchEvent.
