### ISSUE TITLE
literal{} on a sign

### ISSUE THREAD

**Issue by Misha4ek** [PlayPro/CoreProtect#583]
Im hosting a server with mods, via default fabric core, plugins work using cardboard mod.
Every time someone edit and escape sign menu, every line of text appears inside plain text literal{}
On screenshot I edited and exit menu 2 times.
https://cdn.discordapp.com/attachments/1260539566998294548/1260539603669090334/2024-07-10_12.13.22.png?ex=668fb07d&is=668e5efd&hm=b67be4951b91c37dc8b04822ea7ec1956cca6c528a49752d446135d1bf270ed4&

**Comment by vacla** [comment]
Cardboard is not supported and will break plugins.

**Comment by Intelli** [comment]
Not a CoreProtect issue.
