### ISSUE TITLE
Player that died in the nethe desync

### ISSUE THREAD

**Issue by Misha4ek** [PlayPro/CoreProtect#584]
Im hosting a server with mods on my pc. Via default fabric core, plugins work using cardboard mod.
Every time someone dies in the nether and respawns, player spawns with crazy entity offset, that forces player to reconnect to server.
Also players in survival can't move and ofter traped in indestructable blocks underground,
https://cdn.discordapp.com/attachments/1260539566998294548/1260542942985060443/2024-07-10_12.27.12.png?ex=668fb399&is=668e6219&hm=3c4c9a74802bfbf4424f0fdbb029cbb9ad80639cd4edefe6c721f6834c022e9f&
https://cdn.discordapp.com/attachments/1260539566998294548/1260542943476056167/2024-07-10_12.22.34.png?ex=668fb399&is=668e6219&hm=780d4ac932ec7b8fd0ea7daa47067a0169ac0b140110a96058653b3c51913d8d&
https://cdn.discordapp.com/attachments/1260539566998294548/1260542944201408572/2024-07-10_12.22.40.png?ex=668fb399&is=668e6219&hm=2b88d556752fbf64c5157c7328d7f5d36dd27f9f5b5c0fefd1b0348974466973&
https://cdn.discordapp.com/attachments/1260539566998294548/1260542944818106489/2024-07-10_12.22.43.png?ex=668fb399&is=668e6219&hm=9a5b8400f35bcd5adbe734ed4e2e5697a87e39ffb50aca99e1a618859347d70e&
https://cdn.discordapp.com/attachments/1260539566998294548/1260542945317093456/2024-07-10_12.22.56.png?ex=668fb399&is=668e6219&hm=d027ab58acdac7253dac572e39858e1f9f41ad1851a45c48f4800540fb2f2f91&
https://cdn.discordapp.com/attachments/1260539566998294548/1260542945883586741/2024-07-10_12.27.09.png?ex=668fb39a&is=668e621a&hm=237f8bd0121ea057f0a41ea66230d616479dd9eb7748d640c91ea49a46e43b03&

**Comment by vacla** [comment]
Cardboard is not supported and will break plugins

**Comment by Intelli** [comment]
Not a CoreProtect issue
