### ISSUE TITLE
Incompatibility with certain functionalities of the Kingdom plugin

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [PlayPro/CoreProtect#585]
<img width="1058" alt="image" src="https://github.com/PlayPro/CoreProtect/assets/141799770/19cfa22e-5887-4c22-aaab-1ed9aec4e9b0">

**Comment by Intelli** [comment]
To rollback grief in the last 30 days, within a 50 block radius, you can use the following command: 
`/co rollback t:30d r:50`

**Comment by Leoparking** [comment]
> To rollback grief in the last 30 days, within a 50 block radius, you can use the following command: `/co rollback t:30d r:50`

No, I found a big problem. I don't know what's going on, it can't restore the terrain anymore
I'll post a video later
