### ISSUE TITLE
Datapack commands

### ISSUE THREAD

**Issue by RadiantSoul** [PlayPro/CoreProtect#590]
Suggestion:Core protect automatically logging datapack commands like ``execute as player`` that change blocks, like the items in jake's build tools ``https://modrinth.com/datapack/jakes-build-tools`` allowing you to swap blocks you click on with a "chisel" (warped fungus on a stick)

**Comment by Intelli** [comment]
Merged suggestion here: https://github.com/PlayPro/CoreProtect/issues/237
