### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Vupsennc** [PlayPro/CoreProtect#598]
Good afternoon, encountered a problem on the latest version of CoreProtect. Very few details, but removing the plugin fixed the problem.

The server works for some time, at random (or not random) moment after startup plugin starts to create a large number of async threads at once, creates so many that their number exceeds the limit, and the server crashes with the error out of memory. This happens almost instantly. Tried deleting the plugin base, did not help.

Server version 1.16.5. Core purpur. Java 17.

**Comment by Vupsennc** [comment]
Crash Report
https://paste.gg/p/anonymous/a9b86373913a493daafe4f0d00fe03f3

We are 100% sure that CoreProtect is the problem. All other plugins have been checked. And removing CoreProtect showed that the problem disappeared. The RAM is 40GB. Not enough threads.

**Comment by Intelli** [comment]
> CoreProtect v22.2

You’re running an outdated build of CoreProtect

**Comment by Vupsennc** [comment]
I installed the latest version (was pre-previously the latest), the server still crashed.

**Comment by AssassinOWL** [comment]
> > 核心保护 v22.2
> 
> 您正在运行过时的 CoreProtect 版本

I'm sorry for seeking your help in such a sudden way. I need to consult with you on how to use the 2.14.4 plugin version API to write a grade based spigot plugin

import net.coreprotect.CoreProtect;
import net.coreprotect.CoreProtectAPI;

compileOnly name: 'CoreProtect-2.14.4'  

flatDir {
dirs 'libs'
}

This won't make the bag work
