### ISSUE TITLE
CoreProtect logs harmful commands

### ISSUE THREAD

**Issue by ArtemBay** [PlayPro/CoreProtect#604]
Plugin logs auth commands like /reg, /login. Database can be leaked and it can lead to password breach

![image](https://github.com/user-attachments/assets/ad0c6f66-e5a3-4489-b539-ef0e3d4c18eb)

**Comment by CatBang** [comment]
Generally speaking, non-online servers are usually not supported.
But CoreProtect provides a feature to Disabling Logging.

**In the CoreProtect plugin directory, create a file named .**<[blacklist.txt](https://docs.coreprotect.net/config/)>
text content：
> /l
> /reg
> /login
> /register
