### ISSUE TITLE
When do we get a 1.21 version?

### ISSUE THREAD

**Issue by tticehurst** [PlayPro/CoreProtect#623]
It's been many months since the release of mc 1.21 and we're yet to get a non-paid public version of coreprotect

**Comment by Skullians** [comment]
Currently you can compile it yourself for free (I have a guide on CO’s discord if you want it).

as far as we’ve been told, public release is a couple weeks away

**Comment by tticehurst** [comment]
I did end up doing that for my server but I had issues with it not migrating the db over so I had to go hunting for a fix which turned out to just be changing a version number. But it's not very easy to do for those without the technical knowledge.

Just thought I'd ask

**Comment by Skullians** [comment]
If you did not adjust the version in the pom.xml and build.gradle file, patches for your database would not have executed.

**Comment by Skullians** [comment]
The code is for the latest v23.1 plugin, but the versions in Pom.xml and build.gradle are still marked as 22.4

**Comment by tticehurst** [comment]
> The code is for the latest v23.1 plugin, but the versions in Pom.xml and build.gradle are still marked as 22.4

That's what I realised after looking around

**Comment by Strahilchu** [comment]
Just make it premium if you will charge money for it anyway... I'd rather pay one time fee than have to resubscribe to a patreon every 4-5 months when there's an update

**Comment by tticehurst** [comment]
Been hearing "a couple weeks" for a couple months at this point
