### ISSUE TITLE
Unban me on discord

### ISSUE THREAD

**Issue by DaddyRobLIVE** [PlayPro/CoreProtect#628]
![image](https://github.com/user-attachments/assets/2b737ab2-8998-4909-8444-7460cc00ad7a)

I think I got banned a long long time ago when my account got hacked. But it's totally clean and safe now.
Thanks for your understanding.

Here's my discord
![image](https://github.com/user-attachments/assets/cd4b8358-a572-4207-9097-f9eb216ffef1)

**Comment by Intelli** [comment]
The account has been unbanned.
