### ISSUE TITLE
Could not pass event EntityDeathEvent to CoreProtect v23.2-RC1

### ISSUE THREAD

**Issue by LostUmbrella58** [PlayPro/CoreProtect#668]
Server is running on the latest 1.21.1 Paper.
here's the error log: https://pastebin.com/ds1BzC0j
its spamming in the console

**Comment by Intelli** [comment]
Fixed here: https://github.com/PlayPro/CoreProtect/commit/011865de56125ac78e019f0f1932622ed10ef1cd
