### ISSUE TITLE
More Items Info

### ISSUE THREAD

**Issue by IceWolf23** [PlayPro/CoreProtect#67]
Add a window when you move the cursor over the item ID where any enchant and any custom name are reported as has been done for the time elapsed by an action
![IMG_20210810_160011_345.jpg](https://user-images.githubusercontent.com/87717724/128880534-c6145e16-8432-4129-8b8f-3df7e6ba4f66.jpg)

**Comment by Intelli** [comment]
Implemented in https://github.com/PlayPro/CoreProtect/commit/5d6fd60d40281f51fbd248dc7099e008de67b862
