### ISSUE TITLE
NotSerializableException on logging ItemStack with UseCooldownComponent [Spigot Issue]

### ISSUE THREAD

**Issue by YoungSoulluoS** [PlayPro/CoreProtect#682]
CoreProtect - Last Compiled
Minecraft - 1.21.2+
Here is the Issue.
https://hub.spigotmc.org/jira/browse/SPIGOT-7971?filter=-4

**Comment by Skullians** [comment]
What version of CoreProtect are you using? @YoungSoulluoS

**Comment by YoungSoulluoS** [comment]
> What version of CoreProtect are you using? @YoungSoulluoS
Last Community

**Comment by Skullians** [comment]
latest community edition doesn't support 1.21.2 and 1.21.3.
The version that DOES support those versions is only available for Patrons Tier 1+ or you can compile it yourself for free (I have a guide on CoreProtect's discord for this which is very straightforward).

**Comment by YoungSoulluoS** [comment]
Either way it's a bug and will have to be accounted for and wait for a fix for either version.

**Comment by YoungSoulluoS** [comment]
Spigot fixed this bug 8)
