### ISSUE TITLE
Rollback causes items to lose enchants & spawners to revert to the default pig ones

### ISSUE THREAD

**Issue by WanderingLemon** [PlayPro/CoreProtect#69]
On the server that I run when we roll back items that have enchants or enchanted books, they lose their enchants. Another thing happens with spawners where they roll back as the default pig spawner rather than the spawner that they were. Any help in resolving this is much appreciated!

Image of the enchanted book that was rolled back without enchants
![2021-08-15_18 27 15](https://user-images.githubusercontent.com/80416647/129500302-d392a982-3618-412d-a267-44920ac4cab6.png)

**Comment by Intelli** [comment]
Unable to replicate. Please provide a copy of your server log.

**Comment by WanderingLemon** [comment]
Link to pastebin with a console error that appears when using rollback
https://pastebin.com/LM2wGBdw
