### ISSUE TITLE
No Suitable Driver

### ISSUE THREAD

**Issue by ThomasGW120** [PlayPro/CoreProtect#72]
[https://pastebin.com/9HNgEp5y](url)
Hello.  When I start my server, it showed the warning message then disabled CoreProtect. I tried to contact the support of my server host but they said it's the plugin causing the problem. I don't really know how to fix it. Thanks

**Comment by Intelli** [comment]
This issue is likely being caused by another plugin.Please test without any other plugins, and post your full log file if the issue persists.

If removing your plugins resolves the issue, please test adding them back one by one, until you determine which plugin is causing the problem.
