### ISSUE TITLE
[Logs doesn't exist]

### ISSUE THREAD

**Issue by vkerios** [PlayPro/CoreProtect#79]
Info:
MC version: 1.16.1
Core Protect version: 20.1
Ram available: 48GB.
Disk space: 127GB.
 Idk why not log (break block, place block, chat,).. and anything, the configuration is default, all in "true".
I've tried completely remove core protect, restart, and reinstalling again.
plugins:
AnimatedScoreboard, bStats, Chairs, ChatColor2, ChestCommands, ClearLag, ContinionalEvents, CoreProtect, DeathMessages, Essentials, Harbor, HealthBar, InfernalMobs, JoinMessagePlus, LoginSecurity, LuckPerms, MCStatsXYZ, MyCommand, MythicMobs, PlaceHolderAPI, PluginMetrics, ProtocolLib, PvPManager, Quests, SkinsRestorer, TAB, TabCompleteFilter, TabooLib, Vault, WorldEdit,WorldGuard.

pastebin: **https://pastebin.com/G6kxmfCJ**
Thanks for u help! and sorry for the ignorance, and if you need any other information let me know.

edit: Core Protect was one of the first plugins I installed and even at that time it was not getting logs either.

**Comment by vacla** [comment]
@vkerios can you send the full log please?

**Comment by ManiacGamer45** [comment]
@vacla type  /co lookup user:ManiacGamer45 time:1h
replace 'ManiacGamer45' with any user playing and '1h' to any time u want

**Comment by vacla** [comment]
@ManiacGamer45 i know how it works but i mean latest.log or so, to get more info

**Comment by vkerios** [comment]
> @vkerios can you send the full log please?

Yes! i'm sorry. Here's i add other plugins.

https://pastebin.com/N6HiU28j

**Comment by vacla** [comment]
Is there a reason why you are still on 1.16.1 and not on 1.16.5?

**Comment by vkerios** [comment]
> Is there a reason why you are still on 1.16.1 and not on 1.16.5?

The version was chosen by someone else who is no longer there. I always prefer to choose the latter.
Maybe I'll make the switch to 1.16.5 and see if it's works, right?

**Comment by vacla** [comment]
Yeah, also lower the memory 30GB is too much

**Comment by vkerios** [comment]
> Yeah, also lower the memory 30GB is too much

I updated the version from 1.16.1 to 1.16.5. CoreProtect works without problems.
I reduced the amount of ram from 30 to 9 and gradually increased as needed.
Thank you very much Vacla and ManiacGamer for your time and assistance.
