### ISSUE TITLE
Ability to inspect in spectator mode

### ISSUE THREAD

**Issue by Svish** [PlayPro/CoreProtect#83]
I like to do some sporadic checks of my server in spectator mode, to fly around and see what folks have been up to. Found some new buildings and was curious who built them, so I ran `/co inspect`, but clicking on blocks did nothing. Right-clicking did though, it shows the transactions e.g. for chests, but left-clicking doesn't seem to do anything at all.

Is this possible to fix somehow? Kind of annoying to have to jump between spectator and creative/survival whenever I want to inspect something. 😕

**Comment by Intelli** [comment]
If the client isn't passing the click event to the server, then unfortunately, this isn't possible.

**Comment by Svish** [comment]
@Intelli Is it possible to bind it to another key, or something like that?

**Comment by Intelli** [comment]
You can use the `/co l` command to target nearby blocks.

**Comment by Svish** [comment]
Cool, will try that, thanks 🙂
