### ISSUE TITLE
Pistons are not rolled back as expected when moving

### ISSUE THREAD

**Issue by Johnibur** [PlayPro/CoreProtect#92]
### Expected behavior
Pistons are correctly rolled back to pistons in any case.

### Observed behavior
Moving pistons that are destroyed are rolled back to their exact material: `moving_piston`. Yet this block has no render nor hitbox so cannot be broken client side.

### Further information
This is a common problem when rolling back a tnt damaged contraption and creates trails of these unbreakable piston variants. I would suggest that `moving_piston` are rolled back to `piston` instead.

**Comment by Johnibur** [comment]
I've run additional testing, and I'm still able to reproduce with the latest release (20.1) and latest Purpur version.

To reproduce easily, just use 2 observers facing each other and powering a piston; detonate tnt, and you'll have high chances it explodes during piston extending.

**Comment by Intelli** [comment]
Please provide exact steps to replicate the issue, including screenshots of any necessary builds.

**Comment by Intelli** [comment]
Fix will be included in CoreProtect v20.2.
