### ISSUE TITLE
Missing Data of a Chest for Co Inspect

### ISSUE THREAD

**Issue by TheSpiderYT** [PlayPro/CoreProtect#98]
Co Inspect shows that a chest was placed in a location, but there is no data about who broke it or what happened to the chest, no transactions either. The one who placed the chest claims there were valuables in it but no one knows what happened to them. It said the chest was placed 2.11 days ago, I tried rolling back to 1 day, 1.5, and 2 days, still no chest.

**Comment by TheSpiderYT** [comment]
E

**Comment by TheSpiderYT** [comment]
bump

**Comment by vacla** [comment]
@TheSpiderYT can you give us some server info, like which type of server (spigot, paper, magma), server version, coreprotect version (please dont say latest)

**Comment by TheSpiderYT** [comment]
> @TheSpiderYT can you give us some server info, like which type of server (spigot, paper, magma), server version, coreprotect version (please dont say latest)

CoreProtect v20.1.
Paper 1.16.5
