### ISSUE TITLE
[Feature Request] Asynchronous Rollbacks 

### ISSUE THREAD

**Issue by uwuw7** [PlayPro/CoreProtect#99]
This plugin really needs some async rollback features because it is such horrible lag. Tasks really need to be queued up like asyncworldedit because right now my server literally drops to 17tps when trying to rollback even an area of 15 10 hours. If I do anymore it drops down to 14 or 12tps which is practically unplayable borderline crashed for my players. Please consider adding job queues and async tasks in the future.

**Comment by Intelli** [comment]
Rollbacks are already async. Please provide a timings report from during a rollback.

**Comment by uwuw7** [comment]
> Rollbacks are already async. Please provide a timings report from during a rollback.

https://timings.aikar.co/?id=11c18d2904034555ad0aa6285fa93963
